### ISSUE TITLE
Using modules

### ISSUE THREAD

**Issue by timvandam** [OsamaAbbas/bytenode#1]
Is there a way of including npm modules in the compile? Would make it easier to have the same versions of modules running everywhere without having to actually install them on the machine where itll run

**Comment by OsamaAbbas** [comment]
Nice idea. I will connsider adding it in a future release.

**Comment by armizimm** [comment]
bytenode -c scr\*.js  still not work?

A idea to put output directory, ex:  bytenode -c scr\*.js  > ..\bin\.

Went more easy of understand the idea of your project  , than Webassembler.

Congratulations

**Comment by OsamaAbbas** [comment]
`bytenode -c scr*.js` works just fine.

The `output` directory idea is a nice one, I will add it soon.

**Comment by OsamaAbbas** [comment]
All suggested enhancements will be implemented in version 2, hopefully. For now, I will close this issue.
