### ISSUE TITLE
Buffer is undefined in electron

### ISSUE THREAD

**Issue by haakonnessjoen** [OsamaAbbas/bytenode#10]
If I compile a .jsc file inside an electron process with bytenode.compileFile('./test.js', './test.jsc'); and that file contains references to node-js's Buffer object. It is undefined.

So a "new Buffer(1);" gives a ```TypeError: undefined is not a constructor``` exception. And this exception only occurs when requiring the .jsc file of course. The .js file works fine.

**Comment by OsamaAbbas** [comment]
I'll check this. Could you please provide a more specific example?

**Comment by haakonnessjoen** [comment]
Example file test.js:
```var buf = new Buffer(1);```

inside your main.js in electron:

```var v8 = require('v8');
v8.setFlagsFromString('--no-lazy');
bytenode.compileFile('./test.js', './test.jsc');
require('./test.jsc');
```

Result:
```App threw an error during load
TypeError: undefined is not a constructor
    at Object.<anonymous> (evalmachine.<anonymous>:1:167)
    at Object.<anonymous> (evalmachine.<anonymous>:1:185)```

**Comment by OsamaAbbas** [comment]
I can reproduce it now. However, I could not find why the `Buffer` class is not available in the global scope in such a case.

I tried to set `global.Buffer = require('buffer').Buffer` within Bytenode code, but it would be lost when we require '.jsc' files, which is weird. There is something in this case that hijack or remove the global Buffer variable, and only Buffer, any other global variable would survive!

For a quick fix, you can manually require `Buffer` class before you use it, like this:
```JavaScript
const Buffer = require('buffer').Buffer;
```

**Comment by OsamaAbbas** [comment]
Found it. It's not an issue in Bytenode. It's Electron's decision to remove the global Buffer class.

Here: [init.ts#L157](https://github.com/electron/electron/blob/91f81b4b722f7748c3402b00c12266de56f7f054/lib/renderer/init.ts#L157) and [delete-buffer.js#L6](https://github.com/electron/electron/blob/451b1782acfef01dd0758e7b9ddb329700626b98/spec/fixtures/module/delete-buffer.js#L6)

**Comment by haakonnessjoen** [comment]
Seems to me like they redefine it from "const { Buffer } = window". And maybe the default context in electron is not "global" ? Since in the last example you gave, delete-buffer.js, you see them define it via const against "window", and then delete global.Buffer, and then just after, successfully use Buffer as a constructor.

So this seems to work in electron:
```
const { Buffer } = global;
var buf = new Buffer(1);
console.log("Buffer: ", buf.readUInt8(0));
```

Maybe you could prepend "const { Buffer } = global;" to the script when compiling scripts in electron-environment?

**Comment by OsamaAbbas** [comment]
Well, this would solve the problem, but I prefer to wait until we find a better solution. My initial guess is that they have changed the behviour of node `require` function, so the implementation of requiring '.jsc' files, that bytenode adds to `require` function, fails to show electron that `nodeIntegration` is true. Check here: [init.ts#L104](https://github.com/electron/electron/blob/91f81b4b722f7748c3402b00c12266de56f7f054/lib/renderer/init.ts#L104). This could have other consequences than the missing Buffer.

**Comment by OsamaAbbas** [comment]
I wrote a comment then I deleted it. Let me consider your fix and get back to you. My concern is that the cause of this missing Buffer could have other consequences, so we need to know why it happens only with `.jsc` files. It seems to me that Electron, in the case of `.jsc` files, thinks that `nodeIntegration` variable is false.

**Comment by OsamaAbbas** [comment]
I have decided not to fix this as it is not a bug in bytenode itself. It's fairly easy to handle inside your code though.

**Comment by sbrow** [comment]
I am having this problem. Example project [here](https://github.com/sbrow/bytenode-error-example/). While I can solve the problem by adding `Buffer = require("buffer").Buffer` to the top of my file (src/index.js), I think it is a mistake to say that this isn't an issue with bytenode itself.

IMO, if the code works fine when uncompiled, it should work when compiled without changes. The `Buffer` object is available to scripts in the render process if node integration has been enabled.

**Comment by OsamaAbbas** [comment]
> The Buffer object is available to scripts in the render process if node integration has been enabled.

No it is not available, because in case of `.jsc` files, electron –not bytenode– decides to delete the Buffer object.

I could not figure out why –or where– this deletion occur, as the electron source code is not that trivial. I will look into it again.

**Comment by OsamaAbbas** [comment]
Your example has an error.

```
Not allowed to load local resource: file:///home/osama/Desktop/bytenode-error-example/app/index.html
```

**Comment by OsamaAbbas** [comment]
I don't understand why you had to incorporate webpack and all its spells in your example :) . I'm trying to get the app logic to isolate the bytenode aspect of the issue.

However, if you were able to solve the issue and get the app run by adding `Buffer = require("buffer").Buffer`, then you are correct: it's the same issue discussed here. (and it can be demonstrated easily by using `Buffer` object in a very minimal electron setup). So, solving this problem requires that we study the source code of electron itself, to see where exactly the deletion of `Buffer` object occurs, and why this happens in the case of `.jsc` files alone.

I tried this approach before but did not spend much time on it. I'll look into it again and get back to you.
