### ISSUE TITLE
Cross compiling

### ISSUE THREAD

**Issue by valdiss** [OsamaAbbas/bytenode#102]
Hello, first of all thank you for this package, it has helped me a lot!

This is not really an issue but rather a question:

Did you include any cross-compilation capability in this package?

I would like to use this in a CI script to be able to automatically build a version for windows and another one for linux based environments.

Thank you for your time.

**Comment by OsamaAbbas** [comment]
Cross-compilation is not supported, and I don't think that it will ever be supported to be honest. Sorry for that.
