### ISSUE TITLE
Option to create loader files?

### ISSUE THREAD

**Issue by jjeff** [OsamaAbbas/bytenode#111]
Correct me if I'm wrong, but bytenode can't work on its own. `.jsc` files can't be loaded into a Chrome or Electron instance without a `.js` file – a tiny little file like this is all that's needed:

```javascript
require('bytenode');
require('./index.jsc');
```

The [electron-bytenode](https://github.com/spaceagetv/electron-bytenode) module that I've been working on has an option to create these loader files when creating the `.jsc` files. Is that something that you'd be interested in implementing in bytenode?

If so I can put together a pull request. I'd rather not have a separate module for this if it's something that many bytenode users are going to want. And this isn't really an Electron-specific thing anyway.

You can see my work in progress [here](https://github.com/spaceagetv/electron-bytenode/blob/8fbf57cddbebaea0a1390b7239779648fa6a85eb/src/index.ts#L139-L159) and [here](https://github.com/spaceagetv/electron-bytenode/blob/8fbf57cddbebaea0a1390b7239779648fa6a85eb/src/index.ts#L89-L91).

**Comment by OsamaAbbas** [comment]
I like the idea, go ahead and I will accept your pull requests.

If it does not bother you, and for the sake of having the same convention across the board, could you please add the `;` after each line?

**Comment by jjeff** [comment]
Sure! I'll work on that tomorrow.

**Comment by OsamaAbbas** [comment]
> Correct me if I'm wrong, but bytenode can't work on its own. `.jsc` files can't be loaded into a Chrome or Electron instance without a `.js` file – a tiny little file like this is all that's needed:
> 
> ```js
> require('bytenode');
> require('./index.jsc');
> ```

While your premise is true (i.e. bytenode can't work on its own), there is another method other than creating that loader file: `node -r bytenode server.jsc`. This should have the exact same effect. Node with "require" bytenode first (and when bytenode runs, the module system will now know how to deal with `.jsc` files), then it will run `server.jsc` file.

**Comment by OsamaAbbas** [comment]
Closed after #112 was merged. Thank you!
