### ISSUE TITLE
how to build distribution .exe file to windows ?

### ISSUE THREAD

**Issue by GKSONG** [OsamaAbbas/bytenode#115]
o. "npm start" successfully works based on Readme.
    https://github.com/OsamaAbbas/bytenode/tree/master/examples/electron-hello-world

o. Then I try to make distribution .exe files and successfully done with .jsc file.
    [ package.json ]  "dist": "electron-builder -w --x64"

o. When it run, the error happened.
       Error: ENOENT: no such file or directory, open './main-window.src.js'

o. Is there any option when I build distribution .exe files.

**Comment by GKSONG** [comment]
o. I set the same electron version (12.0.1) between project and build.

o. After build (npm run dist) run, the dist directory and several files was created.
   In the /dist/win-unpacked/resources directory I did the following action
     (1) asar e app.asar app
     (2) in app directory
          -- copy main-window.src.js to that directory
          -- delete main-window.jsc
          -- bytenode --compile main-window.src.js  
          -- rename main-window.src.jsc to main-window.jsc
      (3) delete app.asar
      (4) asar p app app.asar

o. Then click {mayapplication}.exe under dist/win-unpacked directory.
    But the same message occurred.
          Error: ENOENT: no such file or directory, open './main-window.src.js'

o. Could you tell me what i am missing ?

**Comment by GKSONG** [comment]
Successfully completed based on the other closed-issues.

**Comment by welcome14** [comment]
Hi, can you link the solution Issue?
