### ISSUE TITLE
question: how to use with pm2?

### ISSUE THREAD

**Issue by shajeeck** [OsamaAbbas/bytenode#12]
thanx for this package. How can i start my jsc file with bytenode using pm2?
i am trying to start jsc as a service using pm2

**Comment by OsamaAbbas** [comment]
Maybe using something like this:

```JavaScript
// launcher.js
const bytenode = require('bytenode');

require('./server.jsc');
```

and then:
```bash
pm2 start launcher.js
```

Let me know if this answers your question.

**Comment by valdiss** [comment]
It worked for me, I'm using pm2 with bytenode thank you very much!

**Comment by rushglen** [comment]
Wow! super easy and it works perfectly (the launcher.js example with pm2).
Many thanks.
