### ISSUE TITLE
Version 1.2.0 not compatible with node 10

### ISSUE THREAD

**Issue by sruetzler** [OsamaAbbas/bytenode#120]
Optional chaining is not available in node10 and I think also not in node 12
But in the function compileElectronCode of index.js it is used.

     [exec] /home/build/js-compile/16394/node_modules/bytenode/index.js:65
     [exec]     proc.stdin?.write(javascriptCode);
     [exec]                ^
     [exec]
     [exec] SyntaxError: Unexpected token .
     [exec]     at new Script (vm.js:79:7)
     [exec]     at createScript (vm.js:251:10)
     [exec]     at Object.runInThisContext (vm.js:303:10)
     [exec]     at Module._compile (internal/modules/cjs/loader.js:656:28)
     [exec]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
     [exec]     at Module.load (internal/modules/cjs/loader.js:598:32)
     [exec]     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
     [exec]     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
     [exec]     at Module.require (internal/modules/cjs/loader.js:636:17)
     [exec]     at require (internal/modules/cjs/helpers.js:20:18)
     [exec] Warning: Permanently added '[192.168.70.201]:2022' (ECDSA) to the list of known hosts.
     [exec] /home/build/js-compile/16394/node_modules/bytenode/index.js:65
     [exec]     proc.stdin?.write(javascriptCode);
     [exec]                ^
     [exec]
     [exec] SyntaxError: Unexpected token .
     [exec]     at new Script (vm.js:79:7)
     [exec]     at createScript (vm.js:251:10)
     [exec]     at Object.runInThisContext (vm.js:303:10)
     [exec]     at Module._compile (internal/modules/cjs/loader.js:656:28)
     [exec]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
     [exec]     at Module.load (internal/modules/cjs/loader.js:598:32)
     [exec]     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
     [exec]     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
     [exec]     at Module.require (internal/modules/cjs/loader.js:636:17)
     [exec]     at require (internal/modules/cjs/helpers.js:20:18)

**Comment by juliano09** [comment]
I'm having the same problem with node 10.16.3 using version 1.2.0. In version 1..1.8 everything is working perfectly
`/projeto/node_modules/bytenode/index.js:65                                                                                                                                                                          
    proc.stdin?.write(javascriptCode);                                                                                                                                                                               
               ^                                                                                                                                                                                                     
                                                                                                                                                                                                                     
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opasuite/execMigrations.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
`

**Comment by mrlong** [comment]
me too

npm timing audit body Completed in 1ms
+ bytenode@1.2.0
added 1 package from 1 contributor and audited 1 package in 2.227s
found 0 vulnerabilities

npm timing npm Completed in 2441ms
npm info ok 
/data/ppms-dist/node_modules/bytenode/index.js:65
    proc.stdin?.write(javascriptCode);
               ^

SyntaxError: Unexpected token .
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
bash: line 4: ./dist/SVN-VER.txt: No such file or directory
	zip warning: name not matched: ./dist/*

zip error: Nothing to do! (try: zip -r ppms-dist.zip . -i ./dist/*)
SSH: EXEC: completed after 2,844 ms
SSH: Disconnecting configuration [ppms-dist] ...
ERROR: Exception when publishing, exception message [Exec exit status not zero. Status [12]]
Finished: UNSTABLE

**Comment by OsamaAbbas** [comment]
Seems that the new syntax used here is not supported in node 10.

I will publish a fix soon.

Thank you for reporting.

**Comment by sruetzler** [comment]
Thank you for fixing so fast
