### ISSUE TITLE
Debugging from log

### ISSUE THREAD

**Issue by kumangxxx** [OsamaAbbas/bytenode#13]
Hi, first of all, this is really cool

im planning to use bytenode in one of my production environment,
one issue tho, say my app crashed, any idea how can i pinpoint where is the crash ?

example:
this is the crash log i got from a ```.jsc``` file

```
TypeError: Cannot read property 'push' of undefined
    at Router.get (evalmachine.<anonymous>:1:250)
    at Layer.handle [as handle_request] (/home/engineer2/Vouch/sandbox/nexe-test/node_modules/express/lib/router/layer.js:95:5)
...
...
```

from that, i can't really see which line is the culprit.
just want to hear your thought on this, 
i'm guessing this is a trade off for using this kind of tool ?

thanks!

---
edit:

also, theoretically, is there a way to reverse engineer complied file ?

**Comment by OsamaAbbas** [comment]
Thank you for your positive feedback.

As far as I know, V8 does minify scripts before compiling them into bytecode. If you compile the minified version vs the documented version of lodash (for example), you will get almost the same result.

So, just as you can't easily debug the minified version of your scripts, you can't easily debug `.jsc` files. Moreover, the actual plain source code is missing in case of `.jsc`, it gets replaced with empty string.

The only useful information that you will get is the error stack, it will be something like that:
```
ReferenceError: someValue is not defined
    at someFunction (evalmachine.<anonymous>:1:112)
    at otherFunction (evalmachine.<anonymous>:1:149)
    at Object.<anonymous> (evalmachine.<anonymous>:1:165)
    at Object.Module._extensions.(anonymous function) [as .jsc] (/usr/local/lib/node_modules/bytenode/index.js:138:26)
```
Here, you know that the error is ReferenceError and it happened in `someFunction()` that was called inside `otherFunction()`. Now, you can check your source code and fix the problem.

For the other question: Yes, it can be reverse-engineered. With enough effort and time, you can reverse-engineer anything. I don't know precisely how hard de-compiling V8 bytecode is, but I guess it's not an easy task, giving that it's API is constantly changing and somewhat poorly documented. Also, there is no real demand for de-compiling V8 bytecode, not like C# or Java at least. So, your code should be safe, at least in the foreseeable future :).
