### ISSUE TITLE
BUG: runBytecodeFile not working!

### ISSUE THREAD

**Issue by blendsdk** [OsamaAbbas/bytenode#14]
Hi,

I am trying to programmatically run a simple compiled `jsc` file but nothing happens! 

My code is: (index.js)
```
'use strict';

const v8 = require('v8');
const path = require('path');
const bytenode = require('bytenode');

v8.setFlagsFromString('--no-lazy');

const file = path.join(process.cwd(), 'test.jsc');

bytenode.runBytecodeFile(file);
```

test.js (test.jsc)
```
console.log('Hello World');
```

There is no output when running: `node index.js`

What am i doing wrong?

**Comment by OsamaAbbas** [comment]
The `bytenode.runBytecodeFile` function expects direct code (or bytecode). So if your file was compiled using the command line, or it was wrapped with `Module.wrap`; it won't work.

For your `test.jsc` to work and print that message, you have to call `require` function instead of `runBytecodeFile`. If you insist to use `bytenode.runBytecodeFile`, then you must compile `test.jsc` yourself, using `bytenode.compileCode` and `fs.writeFile`.

Maybe the documentation isn't clear in this regard.

**Comment by OsamaAbbas** [comment]
Please let me know if you have any further questions. I'll close this issue now.

**Comment by Blaconix** [comment]
Actually had the same issue, documentation could definitely be improved in that regard. Everything's now working fine.

Many thanks :)

**Comment by OsamaAbbas** [comment]
I managed to use `webpack` to produce a single file or package that preserves any `exports` from the entry script (using `libraryTarget` and some other options`), then I used `bytenode` to compile that single bundle. It worked just fine.

But you are right. I'll clarify documentation on this point.

I'm considering also to introduce a new parameter to `bytenode.compileFile` function, say `compileAsModule`, that defaults to `true` (so we don't break compatibility). That way we can easily compile scripts as a plain set of instructions, not as a commonjs module.

Does this sound good?

**Comment by Blaconix** [comment]
Yeah, sounds amazing. On that note, you could also add an argument to the CLI --compile option to have the same functionality as you described above.

**Comment by blendsdk** [comment]
Thank you

**Comment by OsamaAbbas** [comment]
I pushed a quick and dirty edit. It's a bit messy, but I think it does the job. I had to publish it that way because I'm very busy until next month. I hope you will find the last edits useful.
