### ISSUE TITLE
"http2" module

### ISSUE THREAD

**Issue by nwtgck** [OsamaAbbas/bytenode#15]
Hi, thank you very much for your great project!

I used `bytenode` very much. I had an error "Cannot resolve dependency 'http2'" where I used:

```js
const http2 = require("http2");
```

I confirmed `require("http");` and `require("https");` worked well. Could you tell me `bytenode` currently doesn't support "http2" module?

**Comment by OsamaAbbas** [comment]
Could you please provide a complete reproducible example? I can't reproduce that error. `http2` works fine in my test.

**Comment by nwtgck** [comment]
I'm so sorry. You are right. 

I figured out that my error, "Cannot resolve dependency 'http2'" was caused by another module, not `bytenode`.  `bytenode` is great, there is no issue for me.
