### ISSUE TITLE
Error: Invalid or incompatible cached data (cachedDataRejected)

### ISSUE THREAD

**Issue by louistb** [OsamaAbbas/bytenode#18]
I am trying to compile some nodejs that im using inside and electron app. I used nvm and selected the same versions of node as the node js i use inside the project to run the file compilation. 
But when it try to npm start i get : Error: Invalid or incompatible cached data (cachedDataRejected).

Here you can see the node version used to compile the app is the same as the one running in my project.
![wtf](https://user-images.githubusercontent.com/2654241/57560282-b05ee680-7353-11e9-844d-7e8634d67ae2.png)

Thanks for this awesome tool by the way :)

**Comment by OsamaAbbas** [comment]
You must use electron itself, not Node.js, to compile the code.

Check the electron example to see how it is done.

**Comment by OsamaAbbas** [comment]
Please let me know if the previous comment answers your question.

**Comment by louistb** [comment]
I will try it in the same way as the exampl. For all my view .js files and my other js modules i would still need to compile them in the main.js inside electron after the main window one ?

**Comment by louistb** [comment]
Also i is possible to cp.fork a compiled class ? Thanks alot

**Comment by OsamaAbbas** [comment]
> Also i is possible to cp.fork a compiled class ? Thanks alot

Yes, that's possible.

> For all my view .js files and my other js modules i would still need to compile them in the main.js inside electron after the main window one ?

Well, compiling `.js` files inside the `main.js` file is just one way of doing it. The important thing is that: whatever executable you will use in deployment, must be the same executable you use in compiling your files.

So, you may write a very small electron script that will compile your `.js` files and generate `.jsc` files. Then, use `.jsc` files in the product that end-users will use.

This need some work to be done, but it is not that hard.

If you have any further questions please let me know.

**Comment by louistb** [comment]
Thanks for you help its now working ! Big S/0 for this amazing tool !

**Comment by louistb** [comment]
I am actually still having a problem with child process ! Its seems like even if i require bytenode when i do cp.fork and then give the path to my jsc it says Error: Cannot find module.

**Comment by louistb** [comment]
im also having issues with fs.read and path.resolve could this be related to bytenode ? thanks

**Comment by OsamaAbbas** [comment]
Make sure you have required bytenode, before any statments that require `.jsc` files.

For the other question: please provide a minimal example that can be re-produced.

**Comment by sanskarsakya** [comment]
When packaged with electron builder or electron packager this problem still persists however it works well in development environment.How can we make sure in works after packaging?

**Comment by OsamaAbbas** [comment]
Could you please provide more specific details? Write a minimal electron app and let me know what exactly went wrong.

**Comment by sanskarsakya** [comment]
Thank you for the response. Here is the repository with minimal reproduction. https://github.com/sanskarsakya/electron_package_bug.git . It is exact replication of  electron example with added dependency of electron-builder for packaging. Following error is shown after building the app.
![image](https://user-images.githubusercontent.com/16042198/60771377-00b1b500-a107-11e9-82d8-20fa99977a26.png)

**Comment by OsamaAbbas** [comment]
I have cloned your repository. I ran `npm start` once, so that the `.jsc` file is generated. Then I removed the `main-window.src.js` file. Finally, I ran `npm run dist`. Everything works without issues. I can run the application, both from the `.AppImage` file as well as the `./linux-unpacked/package-test` file.

**Comment by sbrow** [comment]
I have been having some unusual trouble with this error. I have two electron applications (client and server) using bytenode on both the render and main processes. The server works perfectly fine, but the client's render process throws `Error: Invalid or incompatible cached data (cachedDataRejected)`.  Things I have tried:
- **Loading the 'invalid' file in the server app**: When I move the offending file over to the server, it loads fine- so I know that the file compiled correctly.
- **Verify both apps use the same version of  electron**: Both programs are part of a monorepo, so they use the exact same electron binary.

Any idea what could be causing this? It's driving me mad.

Thanks!

**Comment by OsamaAbbas** [comment]
Could you please provide a minimal app so I can reproduce the error?

It seems that you compile the files in your server, then you send it to the client. Did I understand it right?

**Comment by sbrow** [comment]
This actually turned out to be issue #10 in disguise.
