### ISSUE TITLE
encryption cache inheritable/accessible?

### ISSUE THREAD

**Issue by viane** [OsamaAbbas/bytenode#2]
I'm not very sure how is the cache mechanism is implemented but currently I'm having trouble running the compiled code in container.

So If I compile the js to jsc in the build statge, eg.travis then run the app in the container from fresh, it would install the bytenode as new (different copy), and then caused the cache inconsistency problem.

Or maybe enable an option to disable encryptcache?

**Comment by OsamaAbbas** [comment]
Bytenode version is irrelavent. What matters is V8 version. So you have to use the same version of Node.js/V8 for both compiling and running the compiled code.

**Comment by OsamaAbbas** [comment]
Seems that there is a bug. I have tried the same version and arch and it throws an error.

However, bytenode does not use any encryption. It use only what V8 offers.

**Comment by OsamaAbbas** [comment]
I have just updated README.md with this warning: **Do NOT Use it in Production**.

Still working on this issue.

**Comment by viane** [comment]
Thanks for the follow up and my error was `Invalid or incompatible cached data`

If it works as expect, this is really helpful for our product, and I do wish to use it ^ ^

**Comment by OsamaAbbas** [comment]
I will do my best. Thank you for your understanding.

**Comment by OsamaAbbas** [comment]
It seems that we have to build a custom Node.js built, with some changes in V8 as well.

What do you think of this approach? Should we build LTS and Latest versions of Node.js?

Anyways, this means that Bytenode will not work with Electron (unless we built it from scratch too), because its version of node will fail too.

NW.js works just fine. In fact, it is their modifications on Node and V8 that inspired me with the solution.

So again, what do you think?

**Comment by ivandov** [comment]
Hi @OsamaAbbas, I'm the product owner for the team @viane is on. 

I'm not too keen on using a custom Node.JS version in order to run our code. There are significant checks that go into Node's Open Source contributions, which would be hard to replicate for bytenode. Beyond that, our goal is to deliver encrypted proprietary code to our clients. Having to package our runtime with non-official Node.JS binaries would not be acceptable.

Maybe this can be a PR that is submitted to the official Node.JS streams? Have it become part of the Node.JS official runtime?

**Comment by OsamaAbbas** [comment]
The solution in mind is to ignore the checksum test for the compiled bytecode. The current checks render the bytecode invalid if it runs on another CPU, or even if you run node with different flags. I don't know if Node team will accept allowing to add an optional argument that would ignore this process. I will try to send them a pull request.

**Comment by OsamaAbbas** [comment]
A quick update: the solution (if we wanted to implement it in Node itself) is based on changing in /deps/v8, so Node team will not accept it. They don't accept patches for their dependencies. And as you know, it is also not easy to contribute to v8. So, this path is not that straightforward. (By the way, that same exact issue was discussed before and caused some tension in Node.js Core Technical Committee).

The other option is to write a c++ addon to the compiled version.

I think I will do both (a native addon and custom Node.js build). I myself prefer the custom Node.js build.

**Comment by OsamaAbbas** [comment]
I think I have figured out a way to fix this issue, without hacking into Node nor V8, only JavaScript code.

I'll implement it tonight and do some tests, then I will publish the fixed version.

**Comment by OsamaAbbas** [comment]
The last commit  [044d0dd](https://github.com/OsamaAbbas/bytenode/commit/044d0dd9287a34744364c654b650358d55f05f2d) fixes this issue. We did not have to make a custom node build nor a native C++ addon.

**Comment by armizimm** [comment]
Very nice, i'm using and i liking very this.

**Comment by viane** [comment]
Thx for the fix, are you still thinking this is not yet ready for production code?

**Comment by OsamaAbbas** [comment]
Well, in NW.js they faced the same issue with their tool "nwjc", and they have fixed it by patching V8 and removing all bytecode validity checks. Yet, their platform is production ready.

My approach in bytenode was to fix the bytecode itself to make it valid, the "invalidness" here refers to CPU features and flags list hash. So the other checks are still performed. On one hand, this approach seems better, on the other hand, I don't know if some other reasons or cases may cause the bytecode to be rejected. My answer would be: I hope there won't be, as suggested by "deps/v8/src/snapshots/code-serializee.cc" file, which is responsible for checking process.

So, if you have control on what code will be run, nothing external, or untested: use it in production. But please run your tests as usual.

**Comment by OsamaAbbas** [comment]
And I will update the readme with the next commit, which will add bundle command, that will combine all required files (even node_modules) in one compiled file. I expect that I will finish it tonight (GMT+9).
