### ISSUE TITLE
How to compile worker_threads

### ISSUE THREAD

**Issue by Winexcel** [OsamaAbbas/bytenode#25]
Hi, I'm using bytenode, this is a reallly great stuff for protection your code, but i have a problem, the problem is that i can't compile my source project with worker_threads. If i compile it, when i run my project i get this error:

> TypeError [ERR_WORKER_UNSUPPORTED_EXTENSION]: The worker script extension must be ".js" or ".mjs". Received ".jsc"

How can I solve the error? 
Great thanks in advance.

**Comment by OsamaAbbas** [comment]
Could you please provide a minimal working example?

**Comment by OsamaAbbas** [comment]
Right now, you cannot compile the worker script that will be sent to the `new Worker(filename)` function. The API now has "Stability: 1 - Experimental" index, so it's better to wait before working on a fix.

However, you can still protect your software logic. Maybe like this:

```JavaScript
'use strict';

const bytenode = require('bytenode');
const { Worker, isMainThread } = require('worker_threads');

if (isMainThread) {
  console.log('Inside the main thread..');
  new Worker(__filename);
  // here too you can require some protected '.jsc' files
} else {
  console.log('Inside the worker..');
  console.log(isMainThread);
  require('./protected-script.jsc');
}
```

**Comment by leopucci** [comment]
Hey @OsamaAbbas, how are you?
Time has passed. Is there any way to run worker_threads protected?
Thanks for your great work

**Comment by leopucci** [comment]
HI @OsamaAbbas, how are you?
I tried the example above, but no matter what I do, it gives me the 'ERR_WORKER_UNSUPPORTED_EXTENSION'
I tried to omit the ` require('./protected-script);` extension. Even tough it gives me the error message:

```
node:internal/worker:174
        throw new ERR_WORKER_UNSUPPORTED_EXTENSION(ext);
        ^

TypeError [ERR_WORKER_UNSUPPORTED_EXTENSION]: The worker script extension must be ".js", ".mjs", or ".cjs". Received ".jsc"
    at new NodeError (node:internal/errors:370:5)
    at new Worker (node:internal/worker:174:15)
    at Object.addNewWorker (evalmachine.<anonymous>:1:563952)
    at new <anonymous> (evalmachine.<anonymous>:1:563914)
    at evalmachine.<anonymous>:1:708070
    at evalmachine.<anonymous>:1:716755
    at Object.<anonymous> (evalmachine.<anonymous>:1:716794)
    at Object.Module._extensions.<computed> (C:\Program Files\pkg\bytenode\lib\index.js:306:26)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12) {
  code: 'ERR_WORKER_UNSUPPORTED_EXTENSION'
}
```

**Comment by lumix99** [comment]
but now is stable!
