### ISSUE TITLE
Use a jsc file in html (electron)

### ISSUE THREAD

**Issue by luki06** [OsamaAbbas/bytenode#26]
Hi ,
i have an electron project ,i want to try to use a compiled a jsc in a html file how can i do that thanks.

**Comment by OsamaAbbas** [comment]
You should be able to use `.jsc` files wherever the node `require` function is defined. Just `require('bytenode');` some where before, and then require your files as usual.

If you have an issue please write a minimal app that can reproduce it.

**Comment by deformal** [comment]
No that doesnt work either  
the required file, cannot be found by the html file.

**Comment by OsamaAbbas** [comment]
If you have an issue with that point please write a minimal app that reproduce it. Without a specific example there is a little we can do.
