### ISSUE TITLE
Mixed environments

### ISSUE THREAD

**Issue by janneman001** [OsamaAbbas/bytenode#28]
Hi Osama, 
Thanks for your nice product. I use it now in a product of mine. 

As an enhancement would be nice to think about mixed environments. Think about projects that depend on stable lts version of node but new projects use latest.

When developing many IDE tools give the opportunity to work with a certain version of node.
Using bytenode it uses global install and compiles with the current system-wide node.

thanks again.
Jan

**Comment by OsamaAbbas** [comment]
I will consider it. Thank you for the suggestion.
