### ISSUE TITLE
Supporting TypeScript

### ISSUE THREAD

**Issue by zewa666** [OsamaAbbas/bytenode#3]
This looks super interesting, especially the Electron part which is an issue for proprietary apps. One thing that might increase its adoption would be to also support compiling TS files. Of course one can always redirect the CLI to pickup the resulting js files from tsc but having this built-in - maybe with ts-node - would make it even more comfortable.

**Comment by OsamaAbbas** [comment]
To be honest, I dislike TypeScript :) . Also I prefer minimalist unix-style tools. However, I will consider to support ts in a future release, it should not be difficult.

**Comment by zewa666** [comment]
Fair statement, I do prefer VanillaJS as well. But its up to us to be good citizens with the rest of the crowd ;)
Also the minimalistic approach, as long as its not like left-pad, is definitely nice. So in this light it might make sense to expose a kind of preprocess hook so tscompilers and whatever else can jump in and do their transformation before your compiler processes it.

**Comment by OsamaAbbas** [comment]
In fact, I am working on another tool, for the idea suggested in issue#1. That tool will bundle all the modules that your entry script uses and requires, in one file. It is almost finished, and it has that compiler feature that you have mentioned. I will release it as a standalone module. It will be integrated here as well.

Of course browserify or even webpack can be used to package everything before compiling, but as I said: I prefer minimalist tools, webpack is the opposite of minimalism, so I don't want to have it as a dependency here. (I like it and use it some times by the way). Browserify was my first choice, but its bundles will lose any exports your entry file may have (so you can't require your bundle, you can just run it). Also, it does not support dynamic require statements. That's why I chose to create my library.

**Comment by zewa666** [comment]
Sure one could but thats pretty much against the idea of this issue where its about being able to feed the compiler TS files.

**Comment by stevebaldwin21** [comment]
> In fact, I am working on another tool, for the idea suggested in issue#1. That tool will bundle all the modules that your entry script uses and requires, in one file. It is almost finished, and it has that compiler feature that you have mentioned. I will release it as a standalone module. It will be integrated here as well.
> 
> Of course browserify or even webpack can be used to package everything before compiling, but as I said: I prefer minimalist tools, webpack is the opposite of minimalism, so I don't want to have it as a dependency here. (I like it and use it some times by the way). Browserify was my first choice, but its bundles will lose any exports your entry file may have (so you can't require your bundle, you can just run it). Also, it does not support dynamic require statements. That's why I chose to create my library.

This sounds awesome. Have you made any more progress on this?

Thanks.

**Comment by OsamaAbbas** [comment]
Almost done, but I am usually very busy in December. I'll do my best to release that library within a week or two.

Thank you for your interest!

**Comment by stevebaldwin21** [comment]
@OsamaAbbas I've been searching for a project just like you mentioned. Please let me know once you have something for testing :) 👍

**Comment by OsamaAbbas** [comment]
All suggested enhancements will be implemented in version 2, hopefully. For now, I will close this issue.

**Comment by RacerDelux** [comment]
Is there any headway on this @OsamaAbbas ?

**Comment by OsamaAbbas** [comment]
If you are asking about TypeScript: unfortunately, I'm very busy these days. Unless there is a serious bug or issue I can't find time for enhancements. I hope you understand that.

That being said, a solution is already mentioned in the first comment by @zewa666:
> Of course one can always redirect the CLI to pickup the resulting js files from tsc but having this built-in - maybe with ts-node - would make it even more comfortable

Also, you can use webpack to bundle your project, and then compile that bundle using Bytenode. All of these steps can be easily implemented using npm scripts.

If you are asking about the library mentioned in my https://github.com/OsamaAbbas/bytenode/issues/3#issuecomment-440754604 above: It's already published under the name Enpaki (with great help from @stevebaldwin21). It supports custom compilers too. However, it's not integrated in Bytenode yet (and I'm not sure if this is a good idea).
