### ISSUE TITLE
bytenode.runBytecode(helloWorldBytecode);  does not work

### ISSUE THREAD

**Issue by yangmin4052** [OsamaAbbas/bytenode#30]

**Comment by OsamaAbbas** [comment]
Please provide more information so I can reproduce the issue.

**Comment by OsamaAbbas** [comment]
I have tested these three basic lines in both Node LTS (v10.16.3) and Node Current (v12.10.0), both work properly.

```javascript
const bytenode = require('bytenode');
let helloWorldBytecode = bytenode.compileCode(`console.log('Hello World!');`);
bytenode.runBytecode(helloWorldBytecode);
```

So I'm closing this issue now. Feel free to re-open it if you have more details or steps that can reproduce your problem.

**Comment by yangmin4052** [comment]
var path = require('path');
var fs = require('fs');
var bytenode = require('bytenode');
var helloWorldBytecode = fs.readFileSync(path.join(__dirname, 'hello.jsc'))
bytenode.runBytecode(helloWorldBytecode );

I think I should not use it like this

**Comment by yangmin4052** [comment]
var path = require('path');
var fs = require('fs');
var bytenode = require('bytenode');
var helloWorldBytecode = fs.readFileSync(path.join(__dirname, 'hello.jsc'))
bytenode.runBytecode(helloWorldBytecode );

I think I should not use it like this

**Comment by OsamaAbbas** [comment]
Well, change it to:

```javascript
require('bytenode');
require('./hello.jsc');
```
and it should work.

If you want to use `bytenode.runBytecode()`, then you have to compile your file manually, with this parameter `compileAsModule: false`.

Like this:

```javascript
let compiledFilename = bytenode.compileFile({
  filename: '/path/to/your/hello.js',
  output: '/path/to/compiled/hello.jsc',
  compileAsModule: false
});
```

Or

```javascript
let helloWorldBytecode = bytenode.compileCode(`console.log('Hello World!');`);
// then you save this buffer to file yourself
```

Read the docs, it should clarify this point.

**Comment by yangmin4052** [comment]
Thank you very much! It works.
