### ISSUE TITLE
Support for Directory?

### ISSUE THREAD

**Issue by iWinston** [OsamaAbbas/bytenode#31]
```
user@machine:~$ bytenode --compile ./**/*.js
```
This command doesn't compile all .js files actually. 

I had a demo like this, and I ran `bytenode --compile ./**/*.js`.
![image](https://user-images.githubusercontent.com/23229557/65486637-8b6ca980-ded7-11e9-9b3c-5d8af8b40648.png)

Only `a.js` was compiled. Can bytenode support the directory mode? Something like:
```
user@machine:~$ bytenode --compile ./dist
```

**Comment by OsamaAbbas** [comment]
Supporting directory is a good idea. I'll add it in a future release.

Regarding the `./**/*` syntax, have you enabled globstar option in bash?

```
shopt -s globstar
```

You should add it to ~/.bashrc too.

**Comment by iWinston** [comment]
I didn't enable globstar option in bash, because the globstar option requires bash 4.x+.

I have upgraded the bash to 4.x+ and add `shopt -s globstar` to ~/.bashrc now. Then the glob pattern works in bash. Thank you @OsamaAbbas.
![image](https://user-images.githubusercontent.com/23229557/65493149-df31bf80-dee4-11e9-9dce-b6535ee12ae4.png)

There is my way to upgrade the bash (for MacOSX):
```
brew install bash
sudo chpass -s /usr/local/bin/bash
chsh -s /usr/local/bin/bash
```

I think it will be more convenient to support directory than to enable globstar option in bash.

**Comment by OsamaAbbas** [comment]
I will do it. Thank you for the suggestion.
