### ISSUE TITLE
how to use it with pm2?

### ISSUE THREAD

**Issue by yangmin4052** [OsamaAbbas/bytenode#32]
// start.js
var process = require('child_process');
process.exec('npx bytenode app.jsc',function (error, stdout, stderr) {
  if (error !== null) {
    console.log('exec error: ' + error);
  }
});

```bash
 pm2 start start.js
```
Is that right?

**Comment by OsamaAbbas** [comment]
Check https://github.com/OsamaAbbas/bytenode/issues/12.

**Comment by yangmin4052** [comment]
Thank you very much!
