### ISSUE TITLE
Error while upgrading Electron 5.0.8 to Electron 7.1.1

### ISSUE THREAD

**Issue by tindl88** [OsamaAbbas/bytenode#37]
Hi OsamaAbbas!

I'm building an Electron app with Bytenode and faced a weird problem.

I open the app and close it after a few seconds, it works well. But I open and wait a few minutes then close, it throws errors like this:

![err1](https://user-images.githubusercontent.com/4578761/68531548-10a40480-0346-11ea-970e-b9b0bc8e3c2e.png)
![err2](https://user-images.githubusercontent.com/4578761/68531553-17cb1280-0346-11ea-84d9-38fe1bf75f40.png)

Can you give me some suggestions?
Thanks you so much.

Info:	
Windows 10
Node 12.8.1
Electron 7.1.1
Bytenode 1.1.2

**Comment by OsamaAbbas** [comment]
As per usual, I'd ask you for a minimal example that reproduce that issue.

**Comment by OsamaAbbas** [comment]
Closed due to the inactivity. Feel free to re-open it.

**Comment by tindl88** [comment]
Hi @OsamaAbbas 

I have just read **Known Issues and Limitations** and change all arrow functions to `function funcName() {}`, it works perfectly.

Thank you so much.
