### ISSUE TITLE
Support for compiling whole project

### ISSUE THREAD

**Issue by WilianZilv** [OsamaAbbas/bytenode#38]
I don't know if it is already possible to compile the entire project, including the required modules inside the project folder and node_modules.
I wonder if it is possible to compile everything in one giant file. Any tip?

**Comment by OsamaAbbas** [comment]
As mentioned in [`express-hello-world` example](https://github.com/OsamaAbbas/bytenode/blob/master/examples/express-hello-world/README.md):

> [Y]ou can bundle your whole express project using browserify, then compile the bundle file.
> ```
> [sudo] npm install -g browserify
> browserify --node server.js > bundle.js
> bytenode --compile bundle.js
> ```
> Now you have bundle.jsc file that can be run without node_modules.
> ```
> bytenode --run bundle.jsc
> ```

However, browserfiy -as far as I remember- will not keep any `exports` that your entry file may have. If you want this feature, check out my other package, [`enpaki`](https://www.npmjs.com/package/enpaki).
