### ISSUE TITLE
Random crashes in electron when using spawned FFMPEG 

### ISSUE THREAD

**Issue by patrickmichalina** [OsamaAbbas/bytenode#39]
Took me awhile to pinpoint what was causing these random crashes. No logs or error events. Just random crashes usually when clicking the app icon to being the app back in focus on OSX. I have no way to trace this issue, any advice would be great. 

(Not using FFMPEG the compiler code works just great!)

**Comment by OsamaAbbas** [comment]
In order to gather enough information about this possible bug, could you please specify your Electron version?

Also, could you run the same code in Linux (or Windows)?

If you can provide a minimal sample of the problematic usage that would be great, because I did not get exactly how a spawned specific process can cause the crash.

Thank you.

**Comment by patrickmichalina** [comment]
@OsamaAbbas I will try to create a reproduction but may be a little while since the source code I am writing is intended to not be shared publicly. I will need to shave off the simplest case and hope that reproduces it.

Some notes:
- I am using [fuse-box](https://github.com/fuse-box/fuse-box) to bundle the application. It is like Webpack/Rollup.
- Using electron version 8.0.0-beta.3 but have tried all the way down to version 5 with the same result.
- Using [ffmpeg-static](https://github.com/eugeneware/ffmpeg-static) for the prebuilt binaries that are included for a specific platform during the build phase.
- Using [electron-builder](https://github.com/electron-userland/electron-builder)

**Comment by patrickmichalina** [comment]
Had a thought:
Say my project is using Node v12.13.0 but a native dependency was pre-built using some other version, could this cause non-deterministic (random) crashes?

**Comment by H1X4Dev** [comment]
If you have electron version above **4.2.12** you may run into issues. Would suggest downgrading as a bypass for now.

For example jQuery library starts throwing weird things like 
```
Uncaught SyntaxError: Invalid or unexpected token
    at HTMLInputElement.dispatch (C:\fakepath\dist\win-unpacked\resources\app.asar\node_modules\jquery\dist\jquery.js:5237)
    at HTMLInputElement.<anonymous> (C:\fakepath\dist\win-unpacked\resources\app.asar\node_modules\jquery\dist\jquery.js:5044)
```

**Comment by patrickmichalina** [comment]
@H1X4Dev You having the same issues of it being random and with zero logging even to the OS?

**Comment by H1X4Dev** [comment]
@patrickmichalina My app would simply reload itself, since you are on OSX it probably doesn't.

**Comment by OsamaAbbas** [comment]
> If you have electron version above **4.2.12** you may run into issues. Would suggest downgrading as a bypass for now.
> 
> For example jQuery library starts throwing weird things like:
> 
> ```
> Uncaught SyntaxError: Invalid or unexpected token
>     at HTMLInputElement.dispatch (C:\fakepath\dist\win-unpacked\resources\app.asar\node_modules\jquery\dist\jquery.js:5237)
>     at HTMLInputElement.<anonymous> (C:\fakepath\dist\win-unpacked\resources\app.asar\node_modules\jquery\dist\jquery.js:5044)
> ```
> 
> These errors only happen if running through bytenode.

I need a minimal reproducible example to look into the issue. Electron is a foreign land for me, so I need some guidence here :) .

But as a first guess: bytenode works only with Node code. jQuery gets executed in the browser side, so it should not be compiled.

**Comment by H1X4Dev** [comment]
@OsamaAbbas Was able to reproduce it on a sample and uploaded it here: https://github.com/H1X4Dev/bytenode_bug_sample1 (npm install & npm install bytenode -g & npm run build & npm run start)

Modify if bytenode (jsc) should be used or not in index.html. Input the data and click the button, the application crashes and reloads itself. There is a short period of time an error is shown, but not enough time to see what was written.

The issue of reloading only exists for versions above **4.2.12** (npm install electron@4.2.12 --save-dev). In the test case I was using electron@latest.

**Comment by OsamaAbbas** [comment]
I will run the app, but as I expected: jQuery (and any interacting with the DOM, or, any JavaScript code that runs inside the browser) will not he able to decode Bytenode .jsc files.

In other words, you can't use bytenode in any JavaScript code that will run inside Chrome's v8. Only what runs in Node.js's v8.

I will test your app and see if we can get around this issue.

@patrickmichalina  do you think that this is the same issue as yours?

**Comment by OsamaAbbas** [comment]
Please see here: https://github.com/H1X4Dev/bytenode_bug_sample1/pull/1

**Comment by patrickmichalina** [comment]
@OsamaAbbas I still haven’t gotten around to setting up a minimal reproduction but will do so soon! The only code I pass into bytenode is an electron/node bundle after it’s been optimized for production. I have a separate bundle for the renderer process that gets loaded via an http server - so I don’t think I have DOM interactions occurring. I’ll do a code trace and see if I am somehow bundling I shouldn’t be though just in case. 

Again this only happens when I include FFMPEG via spawn child process which makes it extra confusing

**Comment by OsamaAbbas** [comment]
Can you reproduce your own problem without electron? You don't have to show your code, just try to extract the spawned thing and call it from node without electron.

**Comment by OsamaAbbas** [comment]
@patrickmichalina Could you please check if the latest version of Bytenode solves the issue or not?

**Comment by patrickmichalina** [comment]
I believe it might. Haven’t had a crash yet! I’ll keep trying in my dev builds to see how stable it over 36 hours.

**Comment by patrickmichalina** [comment]
Think it is good, thanks!
