### ISSUE TITLE
jsc file content is "undefined" 

### ISSUE THREAD

**Issue by salemanokc** [OsamaAbbas/bytenode#4]
jsc file content is "undefined" with nothing else.  My main-src.js file runs fine.

Getting this error:
Unable to open 'main.js': File not found node_modules/electron/dist/resources/default_app.asar/main.js).

**Comment by OsamaAbbas** [comment]
Could you please provide a sample application so I can reproduce your issue?

**Comment by salemanokc** [comment]
Figured it out.  Won't compile when in debug mode in VS Code.  Ran from terminal and worked perfectly.
