### ISSUE TITLE
invalid or unexpected token at Layer.handle_error

### ISSUE THREAD

**Issue by RezaErfani67** [OsamaAbbas/bytenode#40]
i am using webpack:
```javascript
   new BytenodeWebpackPlugin({
                compileAsModule: true,
            })
```
and use pm2 with launcher:

require('bytenode');
require('./server.jsc');

and then:
pm2 start launcher.js

below error with version 13.3.0
![image](https://user-images.githubusercontent.com/24381986/70204421-af4d3680-1735-11ea-8614-7e60f58d50d3.png)

below error with version 12.13.1
![image](https://user-images.githubusercontent.com/24381986/70205748-60ee6680-173a-11ea-9ad8-6981c17fb61c.png)

**Comment by OsamaAbbas** [comment]
Please provide a complete minimal example that reproduce the issue.

Please not that this is Bytenode repository, not BytenodeWebpackPlugin.

**Comment by RezaErfani67** [comment]
i test it without webpack but the same error occurred...
i use bytenode cli...i cant understand what should i provide you?
after bundling the source code,write this:
```
bytenode -c server.js
```
it produce server.jsc but its not work

**Comment by OsamaAbbas** [comment]
Please show me the source code in `server.js`.

**Comment by RezaErfani67** [comment]
oh i cant do this.... excuse me

**Comment by OsamaAbbas** [comment]
You don't have to put your real source. Try to write a very small example that reproduce the issue.

The error message above indicates that the issue is in your implementation. That's why I'm asking to see what the source is.

**Comment by RezaErfani67** [comment]
i know...
i appreciate  you...
but all of code is inside of bundle.js after webpacking it...
then i cant pick sample of that...
thanks @OsamaAbbas  ☺
