### ISSUE TITLE
Why is compiled code bigger than regular code?

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [OsamaAbbas/bytenode#42]
I tested compiling a 10kb file I had and the resulting `.jsc` file was 19kb.  I really expected it to be way smaller.  Is this expected behavior?  Is the code made longer as a side-effect of making it run faster?

**Comment by OsamaAbbas** [comment]
This is normal, and it does not matter whether your 10kb file was minimized or not, you will get about the same size after compiling it.

Also please note that Bytenode does NOT make your code run faster. The opposite is true: we are turning off the lazy compiling feature, and that makes execution a bit slower, but unnoticeable, hopefully.

Check https://github.com/zertosh/v8-compile-cache , it caches your code and make it run faster, but there is not source code hiding there.

**Comment by MelerEcckmanLawler** [comment]
Thanks for the fast response, I was merely curious.
