### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [OsamaAbbas/bytenode#43]
Uncaught Exception:
    SyntaxError: Invalid or unexpected token
      at Timeout._onTimeout
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

I'm using Electron, and have a file that requires a `.jsc` file which requires a `.jsc` file.  I did use the same Electron to compile these files to bytecode.  And the app was working fine for a minute, until this error randomly popped up.  And everytime I clicked `ok` it popped up again.  I had to use Task Manager to kill the process.  This was an executable created with `electron-builder`.

I probably won't be able to get a minimum example but maybe this will be useful for future reference.

**Comment by OsamaAbbas** [comment]
Can you email me with your example?

**Comment by MelerEcckmanLawler** [comment]
Sent.

**Comment by paulr113** [comment]
Has there been any progress regarding this issue? I’m running into the exact same problem.

**Comment by paulr113** [comment]
Could this issue be related to issue #41 ?

**Comment by s100** [comment]
@paulr113 I can't be sure whether this is the same as issue #41 or not. But if it is, you may be able to fix it by upgrading to `bytenode@1.1.4`, or by downgrading from Node.js 12 to Node.js 10.

**Comment by shmox75** [comment]
![Sans titre](https://user-images.githubusercontent.com/39054055/74104514-bb9aa900-4b55-11ea-9ab5-3bae5904195c.jpg)

I have also error on my first try for electron app, what am I doing wrong I compiled the file using:

```
const bytenode = require('bytenode');

bytenode.compileFile({
  filename: './dispatcher.js',
  output: './dispatcher.jsc' // if omitted, it defaults to '/path/to/your/file.jsc'
});
```

AND in my app:

require('./dispatcher.jsc');

**Comment by qntm** [comment]
You probably need to alter your app to say:

```js
require('bytenode')
require('./dispatcher.jsc')
```

The first line is necessary so that the Node.js module loader can load JSC files - normally it can't.

**Comment by shmox75** [comment]
> ```js
> require('bytenode')
> ```

Thank you, but now I have another error:

![Sans titre](https://user-images.githubusercontent.com/39054055/74124912-2d193c80-4bd4-11ea-8c98-54fce9f76bf1.jpg)

**Comment by shmox75** [comment]
> You probably need to alter your app to say:
> 
> ```js
> require('bytenode')
> require('./dispatcher.jsc')
> ```
> 
> The first line is necessary so that the Node.js module loader can load JSC files - normally it can't.

Thank you, it worked now the problem was resolved by compiling files through electron itself.
I don't understand why it doesn't work by compiling with my local node.js version which is the same version as my electron's nodejs . Maybe I had wrong version in my electron ?

PS: How to check my electron's node.js version ? thanks

**Comment by OsamaAbbas** [comment]
You have to use the exact same executable to compile and to run `.jsc`. This is how v8 caching system work. Any other behavior won't work, even if you use the exact same [numeric] version of Node and v8 itself.

**Comment by OsamaAbbas** [comment]
@MelerEcckmanLawler Could you please update Bytenode to the latest version and check whether your issue is solved?

**Comment by OsamaAbbas** [comment]
I'm closing this issue now due to inactivity. Feel free to reopen it if updating Bytenode did not solve your problem.

**Comment by shmox75** [comment]
@OsamaAbbas I resolved it by compiling through electron.js. Thank you.
