### ISSUE TITLE
Creating app using webpack, electron and bytenode

### ISSUE THREAD

**Issue by smunx** [OsamaAbbas/bytenode#44]
Hi, 
I am trying to create a app using webpack and electron. My end goal is to hide the sources for my application.
I created the bytecode for bundle.js and I am trying to use the bundle.jsc in my index.html
So I did the following 

```
require("bytenode");
module.exports = require("./build/bundle.jsc");
```
Named the above file as dist.js and used in index.html as follows

`<script src="dist.js"></script>
`

When I launch the electron app with `electron .`

I get the following error 

```
Uncaught Error: Invalid or incompatible cached data (cachedDataRejected)
    at Object.Module._extensions.<computed> [as .jsc]
```

bundle.jsc is 2.1MB
Node version is v12.13.0

Thanks,

**Comment by OsamaAbbas** [comment]
Replace this line:

```html
<script src="dist.js"></script>
```

with this code:

```html
<script>
  require("bytenode");
  // put here whatever code is inside your dist.js. For example:
  // require("./build/bundle.jsc").initApp();
</script>
```

Try this and let me know what would happen.

**Comment by smunx** [comment]
No change. I still get the same error.

**Comment by OsamaAbbas** [comment]
How did you compile the files? If you compiled them using node itself they won't work in electron.

Can you reproruce the error in other node or electron versions?

Finally, can you try the same setup but with a much smaller bundle? Think of a hello world example.

**Comment by smunx** [comment]
Hi,
Please find the sample code here --> https://github.com/smunx/bytenode-webpack-react-electron
You can reproduce this error on your side.

Thanks,
S

**Comment by OsamaAbbas** [comment]
As I said in the last comment, you can't compile your code using Node itself and run it inside electron. You must compile them from electron itself. The bytecode that is produced from Node's v8 is NOT compatible with electron even if they had the same exact versions.

So, without running your example, I know that it will throw an error.

Please look into the electron example to see how to compile your code from within electron.

**Comment by smunx** [comment]
I got it to work, I used electron to compile it to bytecode. 
Thanks for the awesome tool !

**Comment by eig980** [comment]
> Hi,
> Please find the sample code here --> https://github.com/smunx/bytenode-webpack-react-electron
> You can reproduce this error on your side.
> 
> Thanks,
> S

Can you repubilsh this sample? I have same promblem (((

**Comment by OsamaAbbas** [comment]
> > Hi,
> > Please find the sample code here --> https://github.com/smunx/bytenode-webpack-react-electron
> > You can reproduce this error on your side.
> > Thanks,
> > S
> 
> Can you repubilsh this sample? I have same promblem (((

Have you read my comments above? Anyways, please open another issue for your problem.

**Comment by MetaiR** [comment]
> > > Hi,
> > > Please find the sample code here --> https://github.com/smunx/bytenode-webpack-react-electron
> > > You can reproduce this error on your side.
> > > Thanks,
> > > S
> > 
> > 
> > Can you repubilsh this sample? I have same promblem (((
> 
> Have you read my comments above? Anyways, please open another issue for your problem.

@eig980 

hey, it is possible, I create a working repo and a quickstart hope it helps who in need,
it took too many searches and examines for me to make it happen but it is finally there with the latest version of electron which is at this time 15.3.0

https://github.com/MetaiR/electronforge_react_bytenode_quickstart
