### ISSUE TITLE
Error: Invalid or incompatible cached data (cachedDataRejected) when running jsc in termux android

### ISSUE THREAD

**Issue by goldalworming** [OsamaAbbas/bytenode#46]
Hi I got error Error: Invalid or incompatible cached data (cachedDataRejected) when running jsc in android

I just compile  echo 'console.log("Hello");' | bytenode --compile - > hello.jsc on osx and run it on termux android and this error show up

**Comment by OsamaAbbas** [comment]
You can't compile on osx and run on android. You have to compile using the exact same Node version on the same arch.

**Comment by goldalworming** [comment]
what if I compile on win 64bit and run it on win 32bit...is it works?

**Comment by OsamaAbbas** [comment]
No, it will not work.
