### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by cyberwlf** [OsamaAbbas/bytenode#5]
Nice idea, but for some reason it doesn't want to work out of the box.  

This example:

```
const bytenode = require('bytenode');

let helloWorldBytecode = bytenode.compileCode(`console.log('Hi there')`)
bytenode.runBytecode(helloWorldBytecode);

```
Produce

```
let dummyCode = ' '.repeat(length);
                      ^

RangeError: Invalid string length
```

```
let length = bytecodeBuffer.slice(8, 12).reduce((sum, number, power) => sum += number * 256 ** power, 0);
let dummyCode = ' '.repeat(length); // length is too big
```
I wonder, what's the magic behind this line?

Node version: v8.9.3, Mac

**Comment by OsamaAbbas** [comment]
I could reproduce it in the same version (v8.9.3) on a Linux machine. I'm looking now for what might be the problem.

However, in Node 10 and 11, your code runs just fine.

**Comment by OsamaAbbas** [comment]
Please update bytenode and try again. Make sure you have the newly published version (bytenode v1.0.1).

**Comment by cyberwlf** [comment]
Cool, it works now. One more question: should it work in Electron in the renderer process?

**Comment by OsamaAbbas** [comment]
Yes, wherever you can use Node.js `require` function, you can use bytenode. Just do `require('bytenode')` somewhere in your code, after that you can require your '.jsc' files as usual.

But of course you can't use '.jsc' as `src` attribute in `<script>` tags.

So, this would work:

```JavaScript
<script>
  const bytenode = require('bytenode');

  let app;

  try {
    app = require('./app.jsc');
  } catch (error) {
    bytenode.compileFile('./app.js'); // this file should not exist in production, if you want to protect your source code
    app = require('./app.jsc');
  }

// use your app functions and classes here
</script>
```

but this will NOT work:
```JavaScript
<script src="./app.jsc"></script>
```

**Comment by cyphercodes96** [comment]
Awesome and amazong work on this package - Looking forward to put good use into it

JSYK whenever I try to bytenode an obfuscated file using JavaScriptObfuscator I get the same rangeError invalid string length exception

Would be awesome if we can somehow resolve this - would add more security whenever the .js file will exist prior to .jsc on production environment ( prior to compilation / deletion of file )

const obfJs = (src, options = {}) => {
  fs.readFile(src, 'utf8', function (err, data) {
    if (err) return console.log('err obfuscation3 to file', err);
    var obfuscationResult = JavaScriptObfuscator.obfuscate(data, Object.assign({}, obfOptions, options));

    fs.writeFile(src, obfuscationResult.getObfuscatedCode(), 'utf8', function (err) {
      if (err) return console.log('err obfuscation4 to file', err);
    });
  });
};

obfJs('./libraries/secured.js');

Then on my electron main.js

const appPath = require('electron-root-path').rootPath;
const obfJs2Byte = (src, options = {}) => {
  console.log('obfuscating js 2 bye');
  try {

    let compiledFilename = bytenode.compileFile({
      filename: appPath + src,
      compileAsModule: true
    });
    console.log(compiledFilename)
  } catch (err) {
    console.log('ERR CAUGHT', err)
  }
  try {
    fs.unlink(appPath + src, (err) => {
      if (err) {
        console.error(err);
        return
      }
    })
  } catch (err) {
    console.error(err)
  }
};
console.log('LOGGING FILE RN');
const bytenode = require('bytenode');
if (!fs.existsSync(appPath + '/secured.jsc')) {
  obfJs2Byte('/secured.js');
}


const Security = require(appPath + '/secured.jsc');

Remove javascript obfuscation and it works like a charm

**Comment by OsamaAbbas** [comment]
I have separated your comment into a new issue. Will get back to you there soon.

Thank you for your interest and kind words.
