### ISSUE TITLE
can bytenode work with Cordova for mobile application?

### ISSUE THREAD

**Issue by onelsonic** [OsamaAbbas/bytenode#54]
Hi there, 
not sure where to post this.

I was wondering if this javascript code compiler can work with Cordova?

Great job by the way!
Thank you

**Comment by OsamaAbbas** [comment]
Of course this is not possible. Cordova does not use or support Node.js.

**Comment by onelsonic** [comment]
ok thank you for your feedback

**Comment by cirospaciari** [comment]
@onelsonic maybe with https://github.com/janeasystems/nodejs-mobile-cordova using nodejs as backend, you can load bytenode but not for the front-end (you can put a AES crypto like "protection") and send it to front-end using cordova bridge. I will make some tests and post
