### ISSUE TITLE
Can you run bytenode .jsc compiled with app using Vue.js

### ISSUE THREAD

**Issue by juancampuzano** [OsamaAbbas/bytenode#55]
I have a normal application that is built in node.js and Vue js. To run the application I have to use an index.html file which in turn calls the .js files.

I am wondering if it is possible to use the files compiled with .jsc with an index.html file that calls them.

So my question is: Is it possible to compile an index.html file in the .jsc format in such a way that it can then be run with bytenode?

**Comment by OsamaAbbas** [comment]
It's not possible, unless you are using Electron or NW.js. Any other browsers that you may use to run that `index.html` file would not understand what these `.jsc` files are, they would not even understand plain `.js` node files.
