### ISSUE TITLE
Can run bytenode .jsc compiled files using Vue.js?

### ISSUE THREAD

**Issue by juancampuzano** [OsamaAbbas/bytenode#56]
I have an application that uses Vue.js, is it possible to use bytenode?

On the other hand, the application in vue js generates an index.html file that imports the .js file using  the ` <script type="text/javascript" src="/static/js/app.js"></script>`  tag. There is a way in which the index.html file can import the .jsc file to work.

**Comment by OsamaAbbas** [comment]
Already answered in your other issue.
