### ISSUE TITLE
It's not good work with puppeteer

### ISSUE THREAD

**Issue by huypn** [OsamaAbbas/bytenode#57]
This is issue: Passed function is not well-serializable
Actually I can wrap function with eval(), but better if package can prevent it.
Thanks!

**Comment by s100** [comment]
@huypn Please provide full steps for reproducing this problem. Explain what you did, what you expected to happen, and what actually happened. Otherwise, it's unlikely that anybody will be able to help you.

**Comment by OsamaAbbas** [comment]
> @huypn Please provide full steps for reproducing this problem. Explain what you did, what you expected to happen, and what actually happened. Otherwise, it's unlikely that anybody will be able to help you.

I can't say more.

Puppeteer should work fine. I don't see why it could cause a problem with bytenode. So explain what is the desired outcome and the actual result.

**Comment by OsamaAbbas** [comment]
Closed due to inactivity.

**Comment by caihaibin1991** [comment]
I have solved it now. 
![image](https://user-images.githubusercontent.com/5326638/177675353-a5b40c73-65be-4f5f-81b1-78093a6f1aa1.png)

![image](https://user-images.githubusercontent.com/5326638/177675611-bd18f48d-fd48-49c8-9286-758ce3ed48fc.png)


`/**
   * @param {Function|string} pageFunction
   * @param {...*} args
   * @return {!Promise<!JSHandle>}
   */
  async evaluateHandle(pageFunction, ...args) {
    const suffix = `//# sourceURL=${EVALUATION_SCRIPT_URL}`;
    let functionText = pageFunction.toString();
    if (helper.isString(pageFunction)&&!functionText.startsWith('async ')) {
      const contextId = this._contextId;
      const expression = /** @type {string} */ (pageFunction);
      const expressionWithSourceUrl = SOURCE_URL_REGEX.test(expression) ? expression : expression + '\n' + suffix;
      const {exceptionDetails, result: remoteObject} = await this._client.send('Runtime.evaluate', {
        expression: expressionWithSourceUrl,
        contextId,
        returnByValue: false,
        awaitPromise: true,
        userGesture: true
      }).catch(rewriteError);
      if (exceptionDetails)
        throw new Error('Evaluation failed: ' + helper.getExceptionMessage(exceptionDetails));
      return createJSHandle(this, remoteObject);
    }

    if (typeof pageFunction !== 'function'&&!functionText.startsWith('async '))
      throw new Error('The following is not a function: ' + pageFunction);

    try {
      new Function('(' + functionText + ')');
    } catch (e1) {
      // This means we might have a function shorthand. Try another
      // time prefixing 'function '.
      if (functionText.startsWith('async '))
        functionText = 'async function ' + functionText.substring('async '.length);
      else
        functionText = 'function ' + functionText;
      try {
        new Function('(' + functionText  + ')');
      } catch (e2) {
        // We tried hard to serialize, but there's a weird beast here.
        throw new Error('Passed function is not well-serializable!');
      }
    }
    let callFunctionOnPromise;
    try {
      callFunctionOnPromise = this._client.send('Runtime.callFunctionOn', {
        functionDeclaration: functionText + '\n' + suffix + '\n',
        executionContextId: this._contextId,
        arguments: args.map(convertArgument.bind(this)),
        returnByValue: false,
        awaitPromise: true,
        userGesture: true
      });
    } catch (err) {
      if (err instanceof TypeError && err.message === 'Converting circular structure to JSON')
        err.message += ' Are you passing a nested JSHandle?';
      throw err;
    }
    const { exceptionDetails, result: remoteObject } = await callFunctionOnPromise.catch(rewriteError);
    if (exceptionDetails)
      throw new Error('Evaluation failed: ' + helper.getExceptionMessage(exceptionDetails));
    return createJSHandle(this, remoteObject);

    /**
     * @param {*} arg
     * @return {*}
     * @this {ExecutionContext}
     */
    function convertArgument(arg) {
      if (Object.is(arg, -0))
        return { unserializableValue: '-0' };
      if (Object.is(arg, Infinity))
        return { unserializableValue: 'Infinity' };
      if (Object.is(arg, -Infinity))
        return { unserializableValue: '-Infinity' };
      if (Object.is(arg, NaN))
        return { unserializableValue: 'NaN' };
      const objectHandle = arg && (arg instanceof JSHandle) ? arg : null;
      if (objectHandle) {
        if (objectHandle._context !== this)
          throw new Error('JSHandles can be evaluated only in the context they were created!');
        if (objectHandle._disposed)
          throw new Error('JSHandle is disposed!');
        if (objectHandle._remoteObject.unserializableValue)
          return { unserializableValue: objectHandle._remoteObject.unserializableValue };
        if (!objectHandle._remoteObject.objectId)
          return { value: objectHandle._remoteObject.value };
        return { objectId: objectHandle._remoteObject.objectId };
      }
      return { value: arg };
    }

    /**
     * @param {!Error} error
     * @return {!Protocol.Runtime.evaluateReturnValue}
     */
    function rewriteError(error) {
      if (error.message.endsWith('Cannot find context with specified id'))
        throw new Error('Execution context was destroyed, most likely because of a navigation.');
      throw error;
    }
  }`

**Comment by caihaibin1991** [comment]
If pass a string, It can work, but If want to get reply params, must modify the source and pass a whole function string.

**Comment by caihaibin1991** [comment]
a better solution....
![image](https://user-images.githubusercontent.com/5326638/177678451-61c8bf8a-cea4-4dc4-9d26-eeb942824e7a.png)

**Comment by huypn** [comment]
Hi, @OsamaAbbas all good work, it's working with puppeteer and working when combine bytenode with electron too.
Thank you @OsamaAbbas 

Just 1 issue, that's compile on M1 chip then can't run on Intel :)

**Comment by OsamaAbbas** [comment]
> Just 1 issue, that's compile on M1 chip then can't run on Intel :)

Nothing can be done here. This limitation is from the v8 engine itself, not even Node.js. 

You have to use the same arch and cpu in both compiling and running your app.
