### ISSUE TITLE
bytenode process remains after child processes crash

### ISSUE THREAD

**Issue by oxygen** [OsamaAbbas/bytenode#62]
Using bytenode 1.1.6 under pm2 or systemd (CentOS 7 and Alpine), 
the bytenode process remains running after child process crash preventing an automatic service restart.

Running bytenode like this:
`bytenode --expose-gc app.jsc`

The crash looks like this:
```

#
--
# Fatal error in , line 0
# Check failed: stack_overflow().
#
#
#
#FailureMessage Object: 0x7ffe02a72d40


```

**Comment by OsamaAbbas** [comment]
Interesting. I will look into this.

**Comment by OsamaAbbas** [comment]
I tried to reproduce your issue but failed (on Node 12.18.0). Could you please provide a minimal example that reproduce the issue?

**Comment by oxygen** [comment]
I’ll try to recreate the conditions and the crash somehow and come back here. Problably next week

**Comment by OsamaAbbas** [comment]
I have closed this issue due to inactivity. If you have an update or question, feel free to comment.
