### ISSUE TITLE
Creating app with bytenode and  electron-packager

### ISSUE THREAD

**Issue by xmrhahnx** [OsamaAbbas/bytenode#65]
Hi there, 
I've successfully compiled the bytenode version of my _server.js_ file (_server.jsc_) via electron and I've written the entrypoint (_main.js_) as follows:

`const bytenode = require('bytenode');
const v8 = require('v8');
v8.setFlagsFromString('--no-lazy');
require('./server.jsc');`

If I try to run `electron ./main.js` everything works fine but as I create the package via electron-packager, the program show me the error 
`Uncaught Error: Invalid or incompatible cached data (cachedDataRejected)
    at Object.Module._extensions.<computed> [as .jsc]`

Any suggestion?

Thank you

**Comment by s100** [comment]
As you say, you need to create `server.jsc` using *exactly the same Node.js runtime* as is used by `electron`. I don't think there's anything the `bytenode` package itself can do to help you here.

@OsamaAbbas It seems like this kind of issue keeps recurring and is consuming a lot of effort. Is there a way we can improve the error messages coming out of `bytenode` so it makes it clearer what happened? *E.g.* can we prefix the output bytecode with some kind of header which indicates exactly which version+platform of Node.js, performed the compilation? Then at run time we can inspect the header, compare it with the current version+platform of Node.js, and if there is a mismatch, throw an exception stating what happened.

**Comment by xmrhahnx** [comment]
@s100 I install the 12.14.1 version of node with nvm. So now I have:
- node version 12.14.1
- electron node version 12.14.1

but nothing changed

**Comment by OsamaAbbas** [comment]
> @s100 I install the 12.14.1 version of node with nvm. So now I have:
> 
> * node version 12.14.1
> * electron node version 12.14.1
> 
> but nothing changed

You HAVE to compile using the SAME electron executable which you will use in your final production. You can NOT use Node.js to compile `.js` to `.jsc` that will be run in Electron.

Please check our [electron example](https://github.com/OsamaAbbas/bytenode/tree/master/examples/electron-hello-world) to see one way of doing it. Basically, your code should have some logic that checks if `some_file.jsc` exists? If not, it will be generated from `some_file.js` on the fly. After first run of your production version, delete `some_file.js` and ship `some_file.jsc` to your users.

**Comment by OsamaAbbas** [comment]
> @OsamaAbbas It seems like this kind of issue keeps recurring and is consuming a lot of effort. Is there a way we can improve the error messages coming out of `bytenode` so it makes it clearer what happened? _E.g._ can we prefix the output bytecode with some kind of header which indicates exactly which version+platform of Node.js, performed the compilation? Then at run time we can inspect the header, compare it with the current version+platform of Node.js, and if there is a mismatch, throw an exception stating what happened.

Seems good idea, but it needs some consideration. My initial thought is that the "mismatches" can occur at many levels, not just the platform and version. We intentionally [ignore or fix](https://github.com/OsamaAbbas/bytenode/blob/master/index.js#L40-L58) some of these mismatches (which I don't fully remember now!). So the whole situation needs to be re-visited again.

I'm now thinking that maybe we could change the error message in Electron and put a link to a page here that explains this error and how to fix it. This will be a lot easier than playing with file headers. What do you think?

**Comment by xmrhahnx** [comment]
@OsamaAbbas Ok, I thought it was sufficient to use `electron` instead of `node` to generate the .jsc file.
Anyway when I use the executable with the code to check if the jsc file is already here, it says that it cannot find the requested file to be compiled.

`ENONET: no such file or directory, open './server.js'`

The server.js file actually is in resources/app folder. Have I to add absolute path to it or something like that?

**Comment by OsamaAbbas** [comment]
> The server.js file actually is in resources/app folder. Is it mandatory to add absolute path to it?

I don't have your exact setup obviously, but it is not mandatory to use an absolute path. No differences between node and bytenode here. Check your setup and make sure that regular node fs functions (and require function) can find your file.

Please check the example and do something similar.

**Comment by xmrhahnx** [comment]
For some reason only putting the absolute path do the job. 
Anyway, now everything is ok. 

Thank you!
