### ISSUE TITLE
Encryption of all files

### ISSUE THREAD

**Issue by keithwbacon** [OsamaAbbas/bytenode#70]
Hi,

Having some issues encrypting all .js files all at once, what is the best suggested method to perform this?  Thanks!

**Comment by OsamaAbbas** [comment]
My favorite approach is to use a third-party package (webpack or so) to create a bundle from the project, then I'd compile that bundle file using bytenode.

Also, check the README.md file:

___________________
* Compile all `.js` files in `./app` directory.
```console
user@machine:~$ bytenode --compile ./app/*.js
```

* Compile all `.js` files in your project.
```console
user@machine:~$ bytenode --compile ./**/*.js
```
Note: you may need to enable `globstar` option in bash (you should add it to `~/.bashrc`):
`shopt -s globstar`
___________________

Not the best solution, and it will need more work (removing the plain .js files .. etc), but it works in most cases.
