### ISSUE TITLE
an error with electron

### ISSUE THREAD

**Issue by wuzhiming** [OsamaAbbas/bytenode#71]
I have some problem when using Electron.

1. start electron and use bytenode to compileFIle at browser process.
2. require the gen jsc file(step 1) ,and restart electron ,it works fine.
3. export theEnvironment Variable `export NODE_OPTIONS="--no-warnings --max-old-space-size=4096"`
4. use command line to start electron again ,it will occur this error.(eg:`Electron/Contents/MacOS/Electron`)
![image](https://user-images.githubusercontent.com/6093737/89511832-fc256780-d804-11ea-9ec5-380a01a5dd13.png)

so.
How to generate jsc file when `--max-old-space-size=4096` is using for electron.

**Comment by OsamaAbbas** [comment]
Changing flags generally can cause such errors. Try to generate your `.jsc` files using the same flags or node options.

**Comment by wuzhiming** [comment]
> Changing flags generally can cause such errors. Try to generate your `.jsc` files using the same flags or node options.

But, if user change their flag, it will cause the same problem again, did you have any other solution?
thanks.

**Comment by OsamaAbbas** [comment]
Unfortunately no, this is how cachedData works in V8. Bytenode is nothing but a thin layer on top of what Node.js/v8 already offer.

If V8 decided that the cachedData is invalid due to the changed flags, the only thing that can be done is to ignore that "flags mismatch" altogether. But this can cause crashes and errors, I'm not very sure if this is the right thing to do.

**Comment by wuzhiming** [comment]
> Unfortunately no, this is how cachedData works in V8. Bytenode is nothing but a thin layer on top of what Node.js/v8 already offer.
> 
> If V8 decided that the cachedData is invalid due to the changed flags, the only thing that can be done is to ignore that "flags mismatch" altogether. But this can cause crashes and errors, I'm not very sure if this is the right thing to do.

okey ,thanks
