### ISSUE TITLE
Production Build with .jsc electron file

### ISSUE THREAD

**Issue by BhuvanRohith** [OsamaAbbas/bytenode#73]
Hey i have a electron-main.jsc file compiled using bytenode. Its working fine when i run in a dev server. But, when i do a production build, the app isnt launching. Is it possible to ship .jsc file as the source for electron. This is my package.json electron builder command - 
electron-builder build --linux -c.extraMetadata.main=build/electron/electron-main.jsc --publish never

**Comment by OsamaAbbas** [comment]
The basic answer is you have to use the production binary to generate the `jsc` files. If you have generated them using dev binaries, they would not work in production.

Pay attention to the binary that will be downloaded by `electron-builder`. Download it yourself and use it to compile your files.

Also, I guess that you can not use a `.jsc` file as your main electron entry file. Just use a plain `.js` file. Inside that file you would put your compile-if-not-exist logic, and require your compiled file.

Check our electron example.

I hope this answers your question.

**Comment by BhuvanRohith** [comment]
Thanks a ton. Its the binary issue. Solved now.

**Comment by pedro-surf** [comment]
Could you guys provide any additional information or steps once again to help me achieve it? 

Where do I get this binary generated by Electron-builder, and how to use it?
I have the same issue, works on dev mode, builds fine but after building doesn't launch and shows the error: 

`build/main-window.jsc not found in '...appPath/Resources/app.asar' `
at compileFile function

Environment:

 "bytenode": "^1.1.7",
 "electron": "9.2.0",
  "electron-builder": "^22.8.0"

Could this have something to do with having [electron-rebuild](url) on devDependencies?
Thanks!

**Comment by pedro-surf** [comment]
@BhuvanRohith could you please help me to compile using binary? Couldn't find it anywhere on docs. In dev server everything works as expected here.

**Comment by vu159951** [comment]
> please help me to compile using binary? Couldn't find it anywhere on docs. In dev server everything works as expected here.

Please disable asar. Use __dirname when use fs.

**Comment by pedro-surf** [comment]
I was able to build, but when I disable asar all the app source is available. I hope there's a way to make it work while keep asar..? Would you guys recommend another build tool which works fine with bytenode? 

Also, how can I properly delete the source? I tried to delete my source within my `main.js` (dump below)

```
['use strict';

const bytenode = require('bytenode');
const fs = require('fs');
const v8 = require('v8');
const path = require('path');

v8.setFlagsFromString('--no-lazy');

const pathToCompiledSrc = path.join(__dirname, 'main-window.jsc');
const pathToSrc = path.join(__dirname, 'main-window.src.js');
if (!fs.existsSync(pathToCompiledSrc)) {
	bytenode.compileFile(pathToSrc, pathToCompiledSrc);
  }
fs.unlinkSync(pathToSrc);
  
require(pathToCompiledSrc);](url)
```

However then, the app only ran fine for the first time. Somehow the .jsc file wasn't kept by default. So I had to comment `fs.unlinkSync`

**Comment by cnscorpions** [comment]
@BhuvanRohith Hi, could you please provide more details? no idea about so-called electron-builder production binary. 😂 Any help will be highly appreciated.

**Comment by OsamaAbbas** [comment]
Guys, what I meant by «electron-builder production binary» is very simple. Whatever electron binary that will be downloaded and released by `electron-builder` (or any other similar tool) that you will find inside your `dist` directory: that is the required binary. That is the binary that will be shipped to the user. So, THAT is the binary that MUST be used to generate your `.jsc` files.

Also, you can install `asar` tool globally, then unpack `app.asar` manually to `app` directory, remove `app.asar` for now (or rename it), compile the files inside `app` directory, then finally you can pack the folder again into `app.asar`.

Hope this helps.

**Comment by cnscorpions** [comment]
@OsamaAbbas thank you, I will have a try. 😁
