### ISSUE TITLE
JS file runs differently then JSC

### ISSUE THREAD

**Issue by mako10110** [OsamaAbbas/bytenode#76]
I coded a scraper using nightmarejs and when i run it with node it works fine but when i run it with bytenode some actions inside stop working and I don't have a clue why.

**Comment by OsamaAbbas** [comment]
I don't have a clue neither.

Please provide a minimal reproducible example. Without a concrete example that shows what goes wrong, there is nothing that we can do.

Also, read the README.md file. At least the known issues and limitations.

**Comment by mako10110** [comment]
```
require('bytenode')
const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true, waitTimeout: 900000 })
var fs = require('fs');


var var2 = 0;
var var3 = 3;


    var message = function(){
      nightmare.goto('https://xxx').wait(1000).evaluate(function(var1,var2,var3,var4){

        for (var i = 0; i < var2; i++) {
          setTimeout(function(){
            document.querySelectorAll('.class')[document.querySelectorAll('.class').length-1].scrollIntoView();
          }, i*2000);
        }

   },array1,var2,var3,var4).wait((var2*3000)+500).then(function(){
     nightmare.evaluate(function(array1,var2,var3,var4){

             var obj = {};
             obj.should = false;

              var x =  document.querySelectorAll('.class');

                 document.querySelectorAll('.class')[var3].click()
                 var username1 = document.querySelectorAll('.class')[0].innerText.replace(`\n`,'').replace(`\n`,'');


                 if (array1.includes(username1)) {
                   obj.should = true;
                   var3 = var3+1;
                 } else {
                       document.querySelectorAll('input')[0].value = var4;

                       array1.push(username1);
                       var3 = var3+1;
                 }

               if (var3 === x.length) {
                 var2 = var2+1;
                 var3 = 0;
               }

           obj.p = var2;
           obj.z = var3;
           obj.n = array1;

          return obj;

        },array1,var2,var3,var4).then(function(x){

           var3 =  x.z;
           var2 =  x.p;
           array1 = x.n;
             if (x.should) {
               message();
             } else {
               nightmare.wait(randomIntFromInterval(10000,50000)).click('input').type('input', `\u000d`).wait(1000).click('a[aria-label="'+button+'"]').then(function(){
                 message();
               console.log(array1);
               })
               .catch(function(error) {
                 message();
                 console.error('Restarting:', error)
               })
             }
             console.log(x);

             var file = fs.createWriteStream('n.txt');
file.on('error', function(err) { /* error handling */ });
x.n.forEach(function(v) { file.write(v + '\n'); });
file.end();

             console.log("done");
         console.log(array1);


           })
           .catch(function(error) {
             message();
             console.error('Restarting:', error)
           })
   })

      .catch(function(error) {
        message();
        console.error('Restarting:', error)
      })
    }

```

**Comment by mako10110** [comment]
This is an example of the code I try to --compile

**Comment by OsamaAbbas** [comment]
I can't run this example, even without bytenode.

I get:

```
/home/osama/Desktop/bytenode-nightmare/example.js:20
   },array1,var2,var3,var4).wait((var2*3000)+500).then(function(){
     ^

ReferenceError: array1 is not defined
.
```

I even tried to write there very basic example from README.md, and it does not work either.

Also, nightmare seems abandoned and not maintained anymore, see: https://github.com/segmentio/nightmare/issues/1605

**Comment by mako10110** [comment]
> I can't run this example, even without bytenode.
> 
> I get:
> 
> ```
> /home/osama/Desktop/bytenode-nightmare/example.js:20
>    },array1,var2,var3,var4).wait((var2*3000)+500).then(function(){
>      ^
> 
> ReferenceError: array1 is not defined
> .
> ```
> 
> I even tried to write there very basic example from README.md, and it does not work either.
> 
> Also, nightmare seems abandoned and not maintained anymore, see: https://github.com/segmentio/nightmare/issues/1605

On I forgot to add array1... My bad is just an empty array needed there. I don't think it works for every site that script because is made of a specific one.

**Comment by OsamaAbbas** [comment]
As I mentioned, I can't even run their simplest example.

Anyways, I believe that `evaluate` function won't work with `bytenode`. This function is meant to be sent to the browser component of the system (electron in case of nightmare and chromium in case of puppeteer) as plain text. So, the bytenode version clearly won't work here.

In puppeteer for example, this error is thrown:

```
Passed function is not well-serializable!
```

Still don't know how to workaround this

**Comment by mako10110** [comment]
Can we somehow take the evaluate parts of the code and ignore those so that they are sent as plain text?

**Comment by OsamaAbbas** [comment]
This needs to be tried. Unfortunately, I don't work on this area right now. You should try it and if you encounter an issue or bug in bytenode itself, please report it. The specifics of your solution (and of puppeteer and nightmare) are beyond the scope of what we do here.

**Comment by mako10110** [comment]
Can you show a path on how to ignore parts of code? is it possible?

**Comment by OsamaAbbas** [comment]
I can think of generating the source code on the fly from string variable. I will try later with puppeteer and get back to you.
