### ISSUE TITLE
Running bytenode compiled application on windows

### ISSUE THREAD

**Issue by ymai** [OsamaAbbas/bytenode#79]
Hi,

I used bytenode to compile a server side nodeJS application, and trying to run the server-win.exe on a windows machine.  Does that windows machine needs NodeJS installed?  If not, do you know where will the stdout goes?  Thanks

Yusuf

**Comment by OsamaAbbas** [comment]
You questions are not clear at all.

> I used bytenode to compile a server side nodeJS application, and trying to run the server-win.exe on a windows machine.

Well, bytenode does not generate `server-win.exe` or any `.exe` files at all.

> Does that windows machine needs NodeJS installed?

Bytenode is a node.js library. So, yes, that machine needs node.js installed. Unless you want to use some solutions that package your app in an executable form.

> If not, do you know where will the stdout goes?

This has nothing to do with bytenode. Could you please explain what you are trying to achieve?
