### ISSUE TITLE
Error in version 4.0.3 of the Electron

### ISSUE THREAD

**Issue by Melksedeklobo** [OsamaAbbas/bytenode#8]
Error: Invalid or incompatible cached data (cachedDataRejected) at Object.Module._extensions.(anonymous function) [as .jsc]

**Comment by OsamaAbbas** [comment]
I could run `hello world` example in 4.0.3. So, Please provide a reproducible example.

**Comment by Melksedeklobo** [comment]
It was my mistake to think it was the version of Electron.

This error:
 "Error: Invalid or incompatible cached data (cachedDataRejected) at Object.Module._extensions.(anonymous function) [as .jsc]"

Was being caused because I was doing it by command prompt:

user@machine:~$ bytenode -c main-window.src.js

And then using the generated file 'main-window.src.jsc' in the main.js file

const bytenode = require('../../');
const fs = require('fs');
const v8 = require('v8');
v8.setFlagsFromString('--no-lazy');
require('./main-window.src.jsc');

![captura de tela 6](https://user-images.githubusercontent.com/9409514/52194148-caab9480-2839-11e9-905f-2713f0436bb2.png)

But so
bytenode.compileFile('./main-window.src.js', './main-window.jsc');
Works very well, thank you.

**Comment by OsamaAbbas** [comment]
Yes, you have to use the exact version on Node and v8 in both compiling and running files. Electron, even if it has a specific version of Node, will have its own version of v8. So, in general, you should not compile using Node in this use case.
