### ISSUE TITLE
Build with .jsc on Mac

### ISSUE THREAD

**Issue by pedro-surf** [OsamaAbbas/bytenode#80]
After building my Electron app in MacOS 10.13, I'm not able to run the app

![image](https://user-images.githubusercontent.com/40304742/95467712-28b84580-0954-11eb-833e-42d8b43a199d.png)

(Target: PKG)

**Comment by OsamaAbbas** [comment]
Could you please provide a hello-world minimal example that mimics your setup and environment?

The error does not seems to lie in bytenode itself. So a reproducible example will help.

**Comment by pedro-surf** [comment]
Sorry, Electron-Builder stuff once again.
Solved by adding the following to package.json

```
"mac": ....
      "binaries": [
        "build/main-window.jsc"
      ],
      "type": "distribution"
```
