### ISSUE TITLE
ReferenceError on bytenode.runBytecode

### ISSUE THREAD

**Issue by justanne** [OsamaAbbas/bytenode#81]
I’m using `electron-store` with `bytenode` API. Compiling works fine with `bytenode.compileCode(payload)` but reading with `bytenode.runBytecode` doesn’t work and gives out an error:

<img width="532" alt="Screen Shot 2020-10-13 at 3 22 46 PM" src="https://user-images.githubusercontent.com/1003597/95833963-e9805f00-0d6e-11eb-8906-b49b57be49b5.png">

The **test** is the value I’m trying to compile and read.

This block is on my main js file where I initally compile the value before storing it.

```js
import bytenode from 'bytenode'
import v8 from 'v8'

v8.setFlagsFromString('--no-lazy’)

…

let saveHkey = bytenode.compileCode(payload.hkey)

config.set('hkey', saveHkey)
```

And this block is on another js file listening for updated changes from the store, and runs the bytecode to get the value back.

```js
config.onDidAnyChange((n, o) => {
  setTimeout(() => {
    let configRequest = config.get('hkey')
    let dataBuffer = Buffer.from(configRequest)

   bytenode.runBytecode(dataBuffer)
  }, 3000)
})
```

I’m curious what I’m probably missing here.

**Comment by OsamaAbbas** [comment]
From the first reading, I feel that this information is not enough to understand what goes wrong. I will look into it again tonight and get back to you.

Can you please provide an example of what does `payload.hkey` look like?

Also, may I suggest that you get rid of all arrow functions and try again?

**Comment by justanne** [comment]
> Can you please provide an example of what does payload.hkey look like?

This is sent from the renderer to the main process

<img width="480" alt="Screen Shot 2020-10-14 at 8 28 24 PM" src="https://user-images.githubusercontent.com/1003597/95988725-e616d180-0e5b-11eb-8ad7-119883b4c760.png">

> Also, may I suggest that you get rid of all arrow functions and try again?

Kind of same error

<img width="532" alt="Screen Shot 2020-10-14 at 8 42 22 PM" src="https://user-images.githubusercontent.com/1003597/95990265-dc8e6900-0e5d-11eb-868c-67a4c6c001e0.png">

**Comment by OsamaAbbas** [comment]
So, what you are in fact trying to do is this:

```javascript
bytenode.compileCode("test");
```

Because `payload.hkey` equals `"test"`. This explain your error. If you just run `test`, you will get a reference error. Because obviously that name `test` isn't defined.

Bytenode is NOT an encryption tool. You can't use it to "protect" a "string" (or any other form of data). So when you tell bytenode to run that buffer, what are really trying to do here is equivalent to this: `eval("test");`, which will throw a ReferenceError as well.
