### ISSUE TITLE
Compile in CI and run on other server

### ISSUE THREAD

**Issue by YannMCX** [OsamaAbbas/bytenode#82]
Hello,

I'm designing a paid Node.JS application for my company and I want to compile the sources of the .js files that run with NodeJS 12 (es5).

We have Gitlab CIs that take care of compiling the sources before integrating them into a debian package.
Then this debian package is installed on a server, where the code has to be launched, however I get the following error:

`throw new Error('Invalid or incompatible cached data (cachedDataRejected)');`

I looked at the previous issues and they all talk about Electron, which I don't use.

A little precision on my CIs, the project has a bytenode dependency in the .json package, and those CIs use the locally installed bytenode binary (./node_modules/.bin/bytenode) in order to compile the sources, finally, the command to launch the app on the final machine is the following:
`./node_modules/.bin/bytenode main.jsc`

And, therefore, it doesn't work, do you have any idea how I can correct that?

Translated with www.DeepL.com/Translator (free version)

**Comment by YannMCX** [comment]
Closing the issue, i need to have the same version of NodeJS between the compile time and the run time.

Using LTS on both fixed my problem.

**Comment by OsamaAbbas** [comment]
You have to use the same arch too, and maybe the same node binaries.
