### ISSUE TITLE
Program hangs when compiled with bytenode -c but works with bytenode.compileFile() in NWJS

### ISSUE THREAD

**Issue by kumarasinghe** [OsamaAbbas/bytenode#84]
When I use `bytenote -c` to compile, the program appears to hang at `require('./app.jsc') `

However if I use `bytenote.compileFile('./app.js')` to compile, it works fine.

Is the bahaviour of `bytenote -c` differs from `bytenote.compileFile()` ?

NWJS version: 0.49.2

**Steps to recreate:**
1. Clone and setup nwjs-hello-world in bytenode repo
2. comment index.html:18  `bytenode.compileFile('main-window.src.js', 'main-window.jsc');`
3. run `bytenode -c main-window.js`
4. `latest-nwjs/nw .`

**Comment by OsamaAbbas** [comment]
You can't compile a JavaScript file using Node.js binary (that is, `bytenode -c filename.js`) and run the compiled file from any other binary (whether it is `electron`, another Node.js version, or `NW.js`).

So, you have to use `bytenode.compileFile()` function, inside `NW.js` itself.

Check the example in `examples` folder to see how can you do it.
