### ISSUE TITLE
Electron preload support

### ISSUE THREAD

**Issue by LoYungSum** [OsamaAbbas/bytenode#85]
Can you add the support for using bytenode for electron preload script?

**Comment by OsamaAbbas** [comment]
bytenode can be used already inside preload script.

If you want to protect the preload script it self, just move your protected code into another file, compile it and call it from preload.js.

![image](https://user-images.githubusercontent.com/3346502/99062812-e3d49e00-25e6-11eb-9788-83905f97f4fe.png)

We can't protect that file without changing Electron itself. This can't be done from bytenode.

I hope this answers your question.

**Comment by LoYungSum** [comment]
Oh, I'll know how to implement it. Thanks for the suggested code

**Comment by ksy1992-dev** [comment]
Hi Osama.
Nice to meet to you.
I did run as you said but I have got an error.

1. I did encrypt preload-webview.js with bytenode.
2. I did import preload-webview.jsc in preload.js

But there was an error.

`unpacked\resources\app.asar\webview\webview.jsc:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { ���5,�h`
