### ISSUE TITLE
Problem with JavaScript Obfuscator package

### ISSUE THREAD

**Issue by OsamaAbbas** [OsamaAbbas/bytenode#86]
_Originally posted by @cyphercodes96 in https://github.com/OsamaAbbas/bytenode/issues/5#issuecomment-727723366_

Awesome and amazing work on this package - Looking forward to put it into good use

JSYK whenever I try to bytenode an obfuscated file using JavaScriptObfuscator I get the same rangeError invalid string length exception

Would be awesome if we can somehow resolve this - would add more security whenever the .js file will exist prior to .jsc on production environment ( prior to compilation / deletion of file )

```
const obfJs = (src, options = {}) => {
  fs.readFile(src, 'utf8', function (err, data) {
    if (err) return console.log('err obfuscation3 to file', err);
    var obfuscationResult = JavaScriptObfuscator.obfuscate(data, Object.assign({}, obfOptions, options));

    fs.writeFile(src, obfuscationResult.getObfuscatedCode(), 'utf8', function (err) {
      if (err) return console.log('err obfuscation4 to file', err);
    });
  });
};
obfJs('./libraries/secured.js');
```

Then on my electron main.js

```
const appPath = require('electron-root-path').rootPath;
const obfJs2Byte = (src, options = {}) => {
  console.log('obfuscating js 2 bye');
  try {

    let compiledFilename = bytenode.compileFile({
      filename: appPath + src,
      compileAsModule: true
    });
    console.log(compiledFilename)
  } catch (err) {
    console.log('ERR CAUGHT', err)
  }
  try {
    fs.unlink(appPath + src, (err) => {
      if (err) {
        console.error(err);
        return
      }
    })
  } catch (err) {
    console.error(err)
  }
};
console.log('LOGGING FILE RN');
const bytenode = require('bytenode');
if (!fs.existsSync(appPath + '/secured.jsc')) {
  obfJs2Byte('/secured.js');
}


const Security = require(appPath + '/secured.jsc');
```

Remove javascript obfuscation and it works like a charm

**Comment by OsamaAbbas** [comment]
@cyphercodes96 , can you please try with a smaller source file? Also, what is the size of the obfuscated file?

**Comment by OsamaAbbas** [comment]
Closed due to inactivity. Feel free to ask for re-open or report a new issue with the required details.

**Comment by cyphercodes96** [comment]
> @cyphercodes96 , can you please try with a smaller source file? Also, what is the size of the obfuscated file?

Barely 500 lines of code - already small source file, unless you want me to try with like 5 lines of code :D

Sorry for the late reply haven't seen this till now

**Comment by OsamaAbbas** [comment]
> Barely 500 lines of code - already small source file, unless you want me to try with like 5 lines of code :D

I don't mean yoyr original source, I mean after you obfuscate it, what is its size?

**Comment by OsamaAbbas** [comment]
Closed again due to inactivity.

**Comment by agentcru** [comment]
Hey there, getting the same issue with a javascript obfuscator/electron combination. Even though this works with the direct output of the obfuscation file it somehow gets messed up when the jsc file gets packed into a .asar. After unpacking I noticed different sizes of the two files: original .jsc has 30kb, unpacked one about 40kb. Both files got exactly the same content

**Comment by SentoxAIO** [comment]
Hey @agentcru, I was wondering if you figured it out yet. Facing the same error atm.

**Comment by agentcru** [comment]
I eventually figured out that the issue was a conversion of file encodings. The output bytenode file is neither in utf8 nor binary or any other actively supported encoding. What worked for me is to handle all the data as a buffer. This combined with compileFile method worked for me

**Comment by SentoxAIO** [comment]
But doesn't every JavaScript file get converted to UTF-16 when executing?

**Comment by SentoxAIO** [comment]
If anyone also has this problem, either use a buffer to decode or just remove the stringArrayEncoding. It's kind of useless anyway, since it only takes secs to reverse.

**Comment by asd281533890** [comment]
Same problem, event if I use the following options for JavaScript-obfuscator. It‘s a low level of obfuscation.
It's no problem after I disabled JavaScriptObfuscator.

`const JavaScriptObfuscator = require('webpack-obfuscator')
module.exports = {
  // ...
  plugins: [
    new JavaScriptObfuscator({
      compact: false,
      rotateStringArray: false,
      shuffleStringArray: false,
      simplify: false,
      stringArray: false
    })
  ]
}`

electron: 11.4.3
vue-cli-plugin-electron-builder: 2.0.0-rc.6 
node: 12.22.1
webpack-obfuscator: 2.5.0
JavaScript-obfuscator: 2.12.0

**Comment by OsamaAbbas** [comment]
> > Barely 500 lines of code - already small source file, unless you want me to try with like 5 lines of code :D
> 
> I don't mean your original source, I mean after you obfuscate it, what is its size?

I have asked this question before and I guess it could be relevant here. Please check its size (and the original file size too).

Also, the issue maybe in JavaScript-obfuscator, so it should be reported there too.

**Comment by asd281533890** [comment]
> > > Barely 500 lines of code - already small source file, unless you want me to try with like 5 lines of code :D
> > 
> > 
> > I don't mean your original source, I mean after you obfuscate it, what is its size?
> 
> ~I have asked this question before and I guess it could be relevant here. Please check its size (and the original file size too).~
> 
> Without a complete reproducible example, there is a little we can do. Please create a complete example that reproduce the issue as simple as `npm install && npm start`. Otherwise, it's not possible for me to struggle with `javascript-obfuscator`, `webpack`, `vue-cli` and `electron` to find an issue that might be in either of them, or even in your own code after all!
> 
> A complete, simple, reproducible example please.

I had the same problem. I will give a complete reproducible example later. If this problem is solved, it will help me a lot. Thank you very much.Bytenode is a great work!

**Comment by asd281533890** [comment]
> > > Barely 500 lines of code - already small source file, unless you want me to try with like 5 lines of code :D
> > 
> > 
> > I don't mean your original source, I mean after you obfuscate it, what is its size?
> 
> ~I have asked this question before and I guess it could be relevant here. Please check its size (and the original file size too).~
> 
> Without a complete reproducible example, there is a little we can do. Please create a complete example that reproduce the issue as simple as `npm install && npm start`. Otherwise, it's not possible for me to struggle with `javascript-obfuscator`, `webpack`, `vue-cli` and `electron` to find an issue that might be in either of them, or even in your own code after all!
> 
> A complete, simple, reproducible example please.



> > > > Barely 500 lines of code - already small source file, unless you want me to try with like 5 lines of code :D
> > > 
> > > 
> > > I don't mean your original source, I mean after you obfuscate it, what is its size?
> > 
> > 
> > ~I have asked this question before and I guess it could be relevant here. Please check its size (and the original file size too).~
> > Without a complete reproducible example, there is a little we can do. Please create a complete example that reproduce the issue as simple as `npm install && npm start`. Otherwise, it's not possible for me to struggle with `javascript-obfuscator`, `webpack`, `vue-cli` and `electron` to find an issue that might be in either of them, or even in your own code after all!
> > A complete, simple, reproducible example please.
> 
> I had the same problem. I will give a complete reproducible example later. If this problem is solved, it will help me a lot. Thank you very much.Bytenode is a great work!

I'm sorry I can't provide a demo project, because I created a demo with vue-cli+electron-builder+javaScript-obfuscator on another computer and there is no problem. The program I had a problem with is on the intranet and could not be taken out. But I found the problem is because of the arrow function! I don’t know why there are many arrow functions in the vue code packaged in electron, even if babel is added by default. As far as I know, I usually use vue to build projects and add babel by default to transpile arrow functions into ordinary functions.

My process of creating the project:
1.vue create demo
2.vue add electron-builder

I finally solved the problem by adding the plugin "@babel/plugin-transform-arrow-functions" to the babel.config.js file in the project root directory.
```
// babel.config.js
module.exports = {
  presets: ['@vue/cli-plugin-babel/preset'],
  plugins: ['@babel/plugin-transform-arrow-functions'] // add this
}
```
However, the debugProtection option of JavaScript-obfuscator still prevents the program from starting (the application window is blank after opening).I only open the "Debug Protection" option at https://obfuscator.io/, you can see that it has inserted a piece of code.Other options of JavaScript-obfuscator are still undetermined.

Thanks again!

**Comment by OsamaAbbas** [comment]
I think that debugProtection and self-defending options both are meant to prevent any alteration in your code. So they have to depend on `Function.prototype.toString()` function (in order to inspect your code), and with bytenode, you cannot in principle use `.toString()` on functions, because the source code is already removed for protection.

**Comment by asd281533890** [comment]
> I think that debugProtection and self-defending options both are meant to prevent any alteration in your code. So they have to depend on `Function.prototype.toString()` function (in order to inspect your code), and with bytenode, you cannot in principle use `.toString()` on functions, because the source code is already removed for protection.

I think you are right!!! I obfuscated the code below in [https://obfuscator.io/](https://obfuscator.io/)
`Function.prototype._toString = Function.prototype.toString
Function.prototype.toString = function (t) {
  console.log("Function.prototype.toString is called")
  return this._toString(t)
}
function hi() {
  console.log("Hello World!");
}
hi();` 

No matter whether debugProtection or self-defending is checked. It outputs:
Function.prototype.toString is called
Hello World!

Thanks very much!
