### ISSUE TITLE
Running Without Node

### ISSUE THREAD

**Issue by wwderw** [OsamaAbbas/bytenode#88]
Would it be possible, if not now, maybe at some point, to run this without needing node etc?
Maybe use node for compilation, then have it spit out "glue code" as well as .jsc file, so it would still be recognized in the browser.  Something along the lines of Nectarjs or even WASM (even though that's more for already compiled languages).

While I like Electron, I would like to use something smaller, but still have source protection.  Something like Neutralinojs or even a simple server that python Eel serves up (both of which depend on webview).

Love the project.  I like developing web apps, but source code protection is also the downside with dynamic languages.  Thanks for this.

**Comment by OsamaAbbas** [comment]
Thank you for your proposal.

As I mentioned before, bytenode is a thin layer built on top of Node.js APIs that expose V8 code cashing part. While chrome has V8 too, browsers don't expose the required parts. Also, the cached code is very sensitive to the version and CPU features and many other variables, making it nearly impossible to use the same cached code for your browser visitors.

So, nothing is likely to happen here. bytenode is tied to Node.js itself, not V8. Also, while bytenode can be used in Electron, there is no direct relation between the two.
