### ISSUE TITLE
Crash on NW.js 0.37.4

### ISSUE THREAD

**Issue by efoxbr** [OsamaAbbas/bytenode#89]
Hi,

I want to report an error I had here and the possible solution.

When invoking the compileCode() function, NW.js 0.37.4 was crashing and closing without an error message here. I noticed then that the crash occurred when calling the createCachedData() function and, to solve it, I just reversed the logic to:

`let bytecodeBuffer = script.cachedData? script.cachedData: (script.createCachedData());`

I do not know what the cons of this solution. This error only occurs in NW.js, in Node with the same version (11.14.0) everything goes well.

**Comment by OsamaAbbas** [comment]
I will look into it today. Thank you for reporting.

**Comment by OsamaAbbas** [comment]
I have tried with the mentioned version, NW.js 0.37.4 (on Linux), both SDK and normal build, but I could not reproduce the issue.

Can you please post a reproducible example that I can run?

Also, NW.js 0.37.4 is fairly old version, and Node 11.x is not supported anymore. Is there anything that make these versions a must for your use-case?

**Comment by efoxbr** [comment]
This error occurred on Windows x64, but it is not a problem for my project, I just wanted to contribute with my report.

I can reproduce the error here with the following code:

```
<html>
<body>
<script>
function start () {
const bytenode = require('bytenode');
let result = bytenode.compileCode('console.log("Hello World!");');
console.log(result)
}
</script>
<input type="button" value="Start" onclick="start()" />
</body>
</html>
```

https://mega.nz/file/i24SjZzB#SFegZza-MVyv3yAIZTqVjJH5c2hbYNG09vkxkuUudcU

I used this version of NW.js in this project because I had trouble compiling the ffi-napi module for the current version of NW.js, so I'm still using the ffi module.

I understand that the version is old and it may not be worth it to touch the bytenode code just for it.

**Comment by OsamaAbbas** [comment]
After some investigating, the problem lies in `NW.js` (C++ code) itself. Whenever the code tries to touch this function `createCachedData` in Windows system, it will crash.

I was about to report it to `NW.js` repository. But found it was already reported there: https://github.com/nwjs/nw.js/issues/7036
