### ISSUE TITLE
especify output file.

### ISSUE THREAD

**Issue by armizimm** [OsamaAbbas/bytenode#9]
Hi, i search but not finded, the way to especify the output file.
So i created thwo files to automatize the process.
Would very nice, if we can especify the path to output file.

First file [ compile.Bat ]
--------------------------------------------------------------
call bytenode --compile %cd%\src\%1.js
move /y %cd%\src\%1.jsc %cd%\bin\. 
--------------------------------------------------------------

Second file [ run.bat ]
--------------------------------------------------------------
MD %cd%\bin\
Del %cd%\bin\. /s /q
Copy %cd%\src\*.json %cd%\bin\. /y

rem List of files to compile

call compile.bat index
call compile.bat router
call compile.bat conn
call compile.bat mongod
call compile.bat cliente\cliente

bytenode %cd%\bin\index.jsc
--------------------------------------------------------------

**Comment by OsamaAbbas** [comment]
This feature will be added in a future release, hopefully soon.

**Comment by OsamaAbbas** [comment]
All suggested enhancements will be implemented in version 2, hopefully. For now, I will close this issue.

**Comment by Kikobeats** [comment]
any update of this? 🙂
