### ISSUE TITLE
calling functions inside .jsc file

### ISSUE THREAD

**Issue by xthdraft** [OsamaAbbas/bytenode#90]
Hi.  I'm having trouble understanding how to call my functions inside the .jsc file in an electron app.  The .js file which I converted to .jsc contains several functions: lets say for example f1(), f2() .. etc  

Inside  the electron app I have:  
const k = require('c:/mypath/myfile.jsc');
querying k in devtools shows k as object {}
I've tried things like f1(),  k.f1 but these show undefined.

Any help would be appreciated.
Thanks.

**Comment by OsamaAbbas** [comment]
Are you sure that you defined your exports correctly?
How did you compile `myfile.jsc` exactly?
If you replace `const k = require('c:/mypath/myfile.jsc');` with `const k = require('c:/mypath/myfile.js');`, what would be the result?

**Comment by xthdraft** [comment]
Thank you for your quick response. I tried your suggestion but no luck.

This is my electron app (xthdraft) structure:


   - /src/index.html
   - /src/package.json
      -  "dependencies": {"bytenode": "^1.1.6"}

In my app code:

   - const remote = require('electron').remote;
   - const bytenode = require('bytenode');
   - bytenode.compileFile('c:/xthdraft/src/js/myfile.js',
   'c:/xthdraft/src/js/myfile.jsc');
   - const k = require('c:/xthdraft/src/js/myfile.jsc');

To note:

   - the electron version is 2.0.18
   - node.js version is: 8.9.3
   - k returns object {} in devtools
   - myfile.js contains f1(), f2() etc
   - attempting to reference functions:
      - k.f1 = undefined
      - f1 = undefined
      - ditto with:
      - const karet = require('c:/xthdraft/src/js/myfile.js');

Hope that helps.
Thanks.

**Comment by OsamaAbbas** [comment]
Are you sure that your `myfile.js` have its `exports` set correctly? Because `.jsc` files are identical to their original files. There is no way that it will drop your exports.

And if your code does not work with `require('c:/xthdraft/src/js/myfile.js');`, so clearly the problem is not in bytenode.

**Comment by OsamaAbbas** [comment]
Closed due to inactivity. Also it is clear that the issue is not in bytenode.
