### ISSUE TITLE
 Cannot find module 'xxxx.jsc'

### ISSUE THREAD

**Issue by viphehe** [OsamaAbbas/bytenode#91]
Hello,

`bytenode/examples/electron-hello-world/`

The code in the example ran incorrectly

**Error: Cannot find module 'xxxx.jsc**'

background.js
```
'use strict';

const bytenode = require('bytenode');
const fs = require('fs');
const v8 = require('v8');
const path = `${process.cwd()}\\src`

v8.setFlagsFromString('--no-lazy');

if (!fs.existsSync(`${path}\\background.jsc`)) {

  bytenode.compileFile(`${path}\\background.main.js`, `${path}\\background.jsc`);
}

require(`${path}\\background.jsc`);
```

```
Node version v14.15.0

Electronic version v10.1.5

Bytenode version v1.1.7
```

**Comment by OsamaAbbas** [comment]
Seems unrelated to bytenode at all. I will look into it when I get to a windows machine, hopefully tonight.

**Comment by viphehe** [comment]
> Seems unrelated to bytenode at all. I will look into it when I get to a windows machine, hopefully tonight.

I look forward to your reply.

**Comment by OsamaAbbas** [comment]
I can't reproduce your error. I copied the electron example, then changed its structure according to your example: it works just fine.

**Comment by cnscorpions** [comment]
@viphehe I am faced with the same issue.
I use path.resolve to get the absoluate path, it may be a workaroud for guys who use windows sys.

```
const bytenode = require("bytenode");
const fs = require("fs");
const v8 = require("v8");
const path = require("path");
const { log: logger } = require("./utils/logger");

v8.setFlagsFromString("--no-lazy");

(() => {
  try {
    // 是否编译过
    if (!fs.existsSync(path.join(__dirname, "index.jsc"))) {
      bytenode.compileFile(
        path.join(__dirname, "index.js"),
        path.join(__dirname, "index.jsc")
      );
    }
    // 引入
    require(path.join(__dirname, "index.jsc"));
  } catch (error) {
    logger.error(error);
  }
})();
```

hope it works 😃
