### ISSUE TITLE
Cannot require bytenode jsc file in electron

### ISSUE THREAD

**Issue by boygiandi** [OsamaAbbas/bytenode#94]
Hi. Please help me in this case. I'm using electron-vuejs template from this https://github.com/SimulatedGREG/electron-vue
This project, it didn't use command `electron .`, but using a js file to start electron. You can check in package.json (https://github.com/SimulatedGREG/electron-vue/blob/master/template/package.json)
`"dev": "node .electron-vue/dev-runner.js",`

When I require bytenode jsc file in this js file (`dev-runner.js`), it works.
But when I require jsc file in src/main/index.js , it show error 

>   ERROR in ./src/main/config.jsc 1:0
>   Module parse failed: Unexpected character '�' (1:0)
>   You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
>   (Source code omitted for this binary file)
>    @ ./src/main/index.js 7:13-36
>    @ multi ./src/main/index.dev.js ./src/main/index.js

Can you please check it ?

**Comment by OsamaAbbas** [comment]
I will look into it and get back to you.

**Comment by OsamaAbbas** [comment]
The `dev-runner.js` file will just spawn the electron process. So you must require bytenode inside `src/main/index.js`.

Put `require('bytenode')` at the top of that file and it should work.

**Comment by boygiandi** [comment]
As I mentioned in the question

But when I require jsc file in src/main/index.js , it show error

> ERROR in ./src/main/config.jsc 1:0
> Module parse failed: Unexpected character '�' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> (Source code omitted for this binary file)
> @ ./src/main/index.js 7:13-36
> @ multi ./src/main/index.dev.js ./src/main/index.js

Did you try it ?

I create a config.js file like this
```
module.exports = {
	a: "1"
}
```
Then I insert these code at top of `src/main/index.js `
```
require('bytenode')
bytenode.compileFile('./src/main/config.js', './src/main/config.jsc');
require('./config.jsc');
console.log(config)
```
And then I run `npm run dev`, it show error: https://i.imgur.com/qfjdbr2.png
Please check

**Comment by OsamaAbbas** [comment]
Oh. That seems related to webpack, which I don't have any experience with.

However, I'll look into it.

**Comment by OsamaAbbas** [comment]
The project uses webpack to bundle everything in `./dist/electron/main.js` when you run `npm run dev`. This is far beyond bytenode  and I really don't have much experience with webpack to deal with its peculiarities and edge cases.

My advice is to start figuring out how to protect your app after packaging and packing it. You don't have to protect it while in development stage. The final product will have a clearer structure and less complex setup.

Also, any `.jsc` files that will be generated in the development stage are NOT guaranteed to work in production.

**Comment by boygiandi** [comment]
thank you

**Comment by zjw4328217** [comment]
if i want to protect it in production,what should i do in this electron-vue,i hope you can answer

**Comment by Exfrin** [comment]
Hey there,
I solved the same problem by using `__non_webpack_require__(fileLocation)` in the main process or `require('electron').remote.require(fileLocation)` in the render process (Vue.js).


Example `main.js`
```
bytenode.compileFile({
    filename: 'src/secret.js',
    output: 'public/secret.jsc',
    compileAsModule: true
});
const fileLocation = path.join(__static, 'secret.jsc'); /* global __static */
const secretFunctions = __non_webpack_require__(fileLocation);
```


Example `HelloWorld.vue`
```
<template>
    <div class="hello">
        <h3>Simple Login Example</h3>
        <label>Username<br /><input type="text" v-model="username" /></label><br /><br />
        <label>Password<br /><input type="password" v-model="password" /></label><br /><br />
        <button @click="login">Login</button>
        <p>Valid user: {{ success }}</p>
    </div>
</template>

<script>
const path = require('path');
const fileLocation = path.join(__static, 'secret.jsc'); /* global __static */
const secretFunctions = require('electron').remote.require(fileLocation);

export default {
    name: 'HelloWorld',
    data() {
        return {
            success: false,
            username: '',
            password: '',
        };
    },
    methods: {
        login() {
            this.success = secretFunctions.login(this.username, this.password);
        },
    },
};
</script>
```
