### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by dwkfcml** [OsamaAbbas/bytenode#95]
I used `bytenode -c index.js` , the following error occurred:

evalmachine.<anonymous>:1
(function (exports, require, module, __filename, __dirname) { import Koa from 'koa';
                                                                     ^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at compileCode (/usr/local/lib/node_modules/bytenode/index.js:28:16)
    at Object.compileFile (/usr/local/lib/node_modules/bytenode/index.js:147:22)
    at /usr/local/lib/node_modules/bytenode/cli.js:47:18
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/bytenode/cli.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)

How can I solve this problem? thanks.

**Comment by dwkfcml** [comment]
<img width="623" alt="WeChat0f0a1346e230ac5ae73eaa45e3b9a4ae" src="https://user-images.githubusercontent.com/26158087/103883459-34b0d080-5118-11eb-9427-5f5e9089aefb.png">

bytenode version 1.1.7
nodejs  v10.5.0
macos 10.14.5

**Comment by OsamaAbbas** [comment]
Using LTS version of Node.js, which is v14.15.4 currently, you will get this error:
```
SyntaxError: Cannot use import statement outside a module
```

So, try to use the CommonJS require function, instead of the es6 imports.

**Comment by piranna** [comment]
I have all my libraries build with ESM modules, is it not possible to use them with `bytenode`? Is there any alternative that's not rewrite my code to use `require`s instead of imports? Maybe `babel`?

**Comment by piranna** [comment]
Could it be possible, the same way we generate CommonJS modules, to add another flag to create ESM ones?

**Comment by aleluff** [comment]
@OsamaAbbas Is there any way to still implement ESM, it appears to be the future of node.
It would be very nice

**Comment by OsamaAbbas** [comment]
The last time I looked into it, it was still experimental and it was hard and confusing to implement. I will look into it again soon, but I cannot promise it will be implemented, as I have little time to spend on the issue.

**Comment by OsamaAbbas** [comment]
Still experimental in 18.x. It became Release candidate in 20.x.

I prefer to wait until it is a stable API. I will see what can be done.

**Comment by aleluff** [comment]
Great =)

**Comment by OsamaAbbas** [comment]
Unfortunately, I was wrong. The `vm.Module` class is still experimental and "is only available with the `--experimental-vm-modules` command flag enabled", as per [Node.js docs](https://nodejs.org/docs/latest-v20.x/api/vm.html#class-vmmodule).

I somehow ended up [in this section](https://nodejs.org/docs/latest-v20.x/api/module.html#customization-hooks) before I wrote my previous comment. This is irrelevant, as we must use the `vm` module for compiling and re-creating the code from the bytecode.

**Comment by aleluff** [comment]
Sorry to bother you but I realy need thid feature asap.
So to ubderstand clearly : do you wait nodejs devs to stabilise VM or is it a more complex task ?

Best

**Comment by piranna** [comment]
@aleluff i offer freelance services and maybe i can help you, send me an email to jesus.leganes.combarro@gmail.com.

**Comment by aleluff** [comment]
@piranna Thanks, right now im just obfuscating esm. Do you have a 
 better idea

**Comment by piranna** [comment]
Yes, in fact I've implemented a tool for @Mafalda-SFU on top of bytenodeify that supports ESM, export modules, obfuscates Code, and support code licensing, and have in my roadmap to add support for signatures too.

**Comment by aleluff** [comment]
Thanks but it will be ok

**Comment by OsamaAbbas** [comment]
My main issue or obstacle with implementing Bytenode using `vm.Module` class is how would we "link" the dependencies. The dependencies of each ESM module must be linked to it explicitly. If we are implementing plain JavaScript files: no problem, we would parse the file for import statements and link them. I don't even know how to tackle this issue when dealing with cachedData (v8 bytecode).

**Comment by OsamaAbbas** [comment]
Another simpler solution is adding an extra step in your setup (which should be fairly easy and straightforward): transpile your ESM code to CommonJS before using Bytenode.

**Comment by aleluff** [comment]
I have to admit that I don't have any idea about dep linking but at least I see your tech problem
I will see about transpilation despite I'am not a huge fan of adding steps

I will tell you if I succeed (if I remember :))
