### ISSUE TITLE
When built with PKG, required JSC script does not run

### ISSUE THREAD

**Issue by connorstevens** [OsamaAbbas/bytenode#97]
If I run my test.js from the previous Issue I opened, the application runs properly. I can now use pkg to build the application, thanks to your help on my previous issue. Running the outputted .exe yields nothing, it starts and then finishes immediately. Perhaps I am requiring the file wrong and the executable isn't resolving it properly? There are no errors.

test.js
```
console.log('running');
const requireJSC = require;
const path = require('path');
require('bytenode');
requireJSC(path.join(__dirname, "index.jsc"));
```

Expected output vs actual output:
![image](https://user-images.githubusercontent.com/25255502/104062386-641f1600-51c8-11eb-9449-cd830c8b2425.png)

**Comment by OsamaAbbas** [comment]
Without a reproducible example or specific details about what is inside `index.js`, there is a little that I can help with.

Can you write a minimal `index.js` that mimic your logic and reproduce the issue, so we can figure out what is the problem?

**Comment by connorstevens** [comment]
Sorry for the delay on this issue. I decided to mess around tonight and try with Nexe. Not sure what it is, but Nexe worked. Thanks for the help in my previous issue!

**Comment by GirkovArpa** [comment]
I don't have any code to share, but I have the same issue when requiring a `.jsc` file from inside a `.jsc` file.
